// ===== LECTURE 02: Operating System Overview — STUDENT =====
// Student-added questions only. Testbank questions are in (js/testbank/lec02.js)
// See GUIDE.md for how to add/edit questions.

if (typeof window.ALL_QUESTIONS === 'undefined') {
  window.ALL_QUESTIONS = [];
}

(function () {
  const lec02_student = [

    // ==================== TRUE / FALSE ====================
    {
      type: 'tf',
      question: 'In serial processing systems, users had direct access to the computer hardware with no operating system present.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'Serial processing was the earliest era — programmers interacted directly with hardware via console switches and display lights.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In a simple batch system, "control is returned to the monitor" means the processor is fetching and executing user program instructions.',
      choices: ['True', 'False'],
      answer: 1,
      hint: '"Control returned to the monitor" means the processor executes monitor instructions, not user program instructions.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'The kernel (nucleus) contains the most-frequently used OS functions and is permanently kept in main memory.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'The kernel is the portion of the OS in main memory containing the most frequently used functions.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In a paging system, a page fault occurs when the referenced page is already present in main memory.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'A page fault occurs when the referenced page is NOT in main memory, triggering a load from secondary storage.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'The short-term scheduling queue contains processes that are ready to run and are in (or partially in) main memory.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'The short-term queue (ready queue) holds in-memory processes that are ready to be assigned the CPU.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Multiprogramming and multiprocessing refer to the same concept: running multiple programs simultaneously.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Multiprogramming means the CPU switches among processes one at a time. Multiprocessing means truly simultaneous execution on multiple processors.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'A microkernel keeps only essential functions (IPC, basic scheduling) in the kernel and runs services such as device drivers as user-mode servers.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'This is the defining characteristic of a microkernel: minimal privileged code, with services delegated to user-space.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In Symmetric Multiprocessing (SMP), each processor is assigned a fixed, distinct set of tasks and cannot perform the functions of other processors.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'In SMP, all processors share memory and I/O and can all perform the same functions — no fixed role assignment.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Fault tolerance relies on redundancy to allow a system to continue operation despite hardware or software faults.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'Redundancy — spatial, temporal, or informational — is the core mechanism behind fault tolerance.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'A transient fault is a type of permanent fault that requires component replacement to recover.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'A transient fault is a temporary fault that occurs only once. Permanent faults persist until repaired or replaced.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Availability is defined as the fraction of time the system is available to service requests.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'Availability = MTTF / (MTTF + MTTR), representing the proportion of time the system is operational.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In a layered OS architecture, each layer relies on the services of layers above it and provides services to layers below.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'It is the opposite: each layer relies on layers BELOW it and provides services to layers ABOVE it.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Android is a Linux-based mobile operating system originally designed for mobile phones.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'Android uses the Linux kernel as its base and was designed for mobile devices.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'SVR4 (System V Release 4) was developed solely by AT&T with no collaboration from other companies.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'SVR4 was developed jointly by AT&T and Sun Microsystems, combining features from SVR3, 4.3BSD, Xenix, and SunOS.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Temporal redundancy is effective against permanent faults because repeating the operation will eventually yield a correct result.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Temporal redundancy (repeating an operation) is only effective against temporary faults — it cannot fix a permanent fault.',
      figure: null,
    },

    // ==================== MULTIPLE CHOICE ====================
    {
      type: 'mcq',
      question: 'Which of the following is NOT one of the three main objectives of an operating system?',
      choices: [
        'Convenience',
        'Efficiency',
        'Ability to evolve',
        'Maximizing hardware lifespan',
      ],
      answer: 3,
      hint: 'The three OS objectives are convenience, efficiency, and ability to evolve. Hardware lifespan is not included.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'When a virtual address is not found in main memory, what event is triggered?',
      choices: [
        'Context switch',
        'Page fault',
        'Interrupt masking',
        'Trap instruction',
      ],
      answer: 1,
      hint: 'A page fault occurs when the processor references a virtual page not currently in main memory, triggering a load from disk.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which OS queue holds new jobs waiting for the OS to admit them into active memory?',
      choices: [
        'Short-term queue',
        'I/O queue',
        'Long-term queue',
        'Ready queue',
      ],
      answer: 2,
      hint: 'The long-term queue (job pool) buffers new jobs before they are admitted to the short-term ready queue.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which of the following is NOT a process coordination issue that contributed to the development of the process concept?',
      choices: [
        'Improper synchronization',
        'Failed mutual exclusion',
        'Memory fragmentation',
        'Deadlocks',
      ],
      answer: 2,
      hint: 'The four coordination issues are: improper synchronization, failed mutual exclusion, non-determinate operations, and deadlocks. Memory fragmentation is a memory management concern.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which type of redundancy involves replicating or encoding data so that bit errors can be detected and corrected?',
      choices: [
        'Spatial redundancy',
        'Temporal redundancy',
        'Information redundancy',
        'Process redundancy',
      ],
      answer: 2,
      hint: 'Information redundancy adds extra data (e.g., error-correcting codes) to detect and correct bit errors in stored or transmitted data.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which measure represents the average time between the start of operation and the first failure of a system?',
      choices: [
        'MTTR',
        'Availability',
        'MTTF',
        'Reliability R(t)',
      ],
      answer: 2,
      hint: 'MTTF (Mean Time To Failure) measures how long a system operates correctly before failing.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'In the hierarchical OS model, which level handles virtual memory (segments and pages)?',
      choices: [
        'Level 1 — Electronic circuits',
        'Level 3 — Procedures',
        'Level 5 — Primitive processes',
        'Level 7 — Virtual Memory',
      ],
      answer: 3,
      hint: 'Level 7 in the hierarchical model deals with virtual memory, segments, and pages with read/write/fetch operations.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which of the following is a key benefit of microkernel architecture?',
      choices: [
        'Higher performance since everything runs in kernel mode',
        'Extensibility and portability due to modular user-space service structure',
        'Simpler development since all services share the same address space',
        'Reduced need for inter-process communication',
      ],
      answer: 1,
      hint: 'Microkernels offer extensibility, flexibility, portability, and reliability because services run as isolated user-mode modules.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'What is the key difference between emulation and virtualization in virtual machines?',
      choices: [
        'Emulation runs the guest OS natively; virtualization translates every instruction',
        'Emulation translates every instruction; virtualization lets the guest OS run natively',
        'Emulation and virtualization are identical techniques',
        'Virtualization only handles hardware simulation; emulation handles only software',
      ],
      answer: 1,
      hint: 'Emulation is slow because it translates every instruction. Virtualization is faster because the guest OS runs natively with the VMM providing virtualization services.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which Android Application Framework component manages the lifecycle of application activities?',
      choices: [
        'Window Manager',
        'Package Manager',
        'Activity Manager',
        'Content Provider',
      ],
      answer: 2,
      hint: 'The Activity Manager in the Android Application Framework manages the lifecycle of activities (screens/UI components).',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which UNIX-based BSD variant is specifically known for its focus on security?',
      choices: [
        'FreeBSD',
        'NetBSD',
        'OpenBSD',
        'Solaris',
      ],
      answer: 2,
      hint: 'OpenBSD is a BSD variant specifically focused on security, code correctness, and cryptography.',
      figure: null,
    },

    // ==================== LIST ====================
    {
      type: 'list',
      question: 'List the four stages in the evolution of operating systems.',
      choices: null,
      answer: [
        'Serial Processing',
        'Simple Batch Systems',
        'Multiprogrammed Batch Systems',
        'Time Sharing Systems',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the five major achievements in operating system design.',
      choices: null,
      answer: [
        'Processes',
        'Memory management',
        'Information protection and security',
        'Scheduling and resource management',
        'System structure',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the four process coordination issues that drove the development of the process concept.',
      choices: null,
      answer: [
        'Improper synchronization',
        'Failed mutual exclusion',
        'Non-determinate operations',
        'Deadlocks',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the five developments that led to modern operating systems.',
      choices: null,
      answer: [
        'Microkernel architecture',
        'Multithreading',
        'Symmetric multiprocessing (SMP)',
        'Distributed OS',
        'Object-oriented design',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the four security categories that OS protection is grouped into.',
      choices: null,
      answer: [
        'Availability',
        'Confidentiality',
        'Data integrity',
        'Authenticity',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the three types of OS scheduling queues and describe what each holds.',
      choices: null,
      answer: [
        'Short-term (ready) queue — processes in or partially in memory, ready to run',
        'Long-term (job pool) queue — new jobs waiting to be admitted into memory',
        'I/O queues — per-device queues of processes waiting for I/O completion',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the three methods of redundancy used in fault tolerance.',
      choices: null,
      answer: [
        'Spatial (physical) redundancy — multiple components perform the same function simultaneously or as backups',
        'Temporal redundancy — repeat the operation when an error is detected (for temporary faults)',
        'Information redundancy — replicate or encode data to detect and correct errors',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the four OS mechanisms used to support fault tolerance.',
      choices: null,
      answer: [
        'Process isolation',
        'Concurrency controls',
        'Virtual machines',
        'Checkpoints and rollbacks',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the three components of a process.',
      choices: null,
      answer: [
        'Executable program',
        'Associated data (variables, workspace, buffers, stacks)',
        'Execution context (internal data used by the OS to control the process)',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the five storage management responsibilities of an OS.',
      choices: null,
      answer: [
        'Process isolation',
        'Automatic allocation and management',
        'Support of modular programming',
        'Protection and access control',
        'Long-term storage',
      ],
      figure: null,
    },

    // ==================== DEFINE ====================
    {
      type: 'define',
      question: 'Define a "page fault" in virtual memory.',
      choices: null,
      answer: 'A page fault occurs when a process references a virtual page that is not currently present in main memory, causing the OS to suspend the process and load the required page from secondary storage (disk).',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "availability" as a fault tolerance measure.',
      choices: null,
      answer: 'Availability is the fraction of time a system is operational and able to service requests. It equals MTTF / (MTTF + MTTR), where MTTF is Mean Time To Failure and MTTR is Mean Time To Repair.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define a "thread" in the context of multithreading.',
      choices: null,
      answer: 'A thread is a dispatchable unit of work that has its own processor context (program counter and stack pointer) and stack area. Multiple threads can exist within a single process, sharing the same resources and address space.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "Symmetric Multiprocessing (SMP)".',
      choices: null,
      answer: 'SMP is a hardware/OS configuration where two or more processors share the same main memory and I/O and can all perform the same OS functions. The OS can schedule any process or thread on any available processor.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "microkernel architecture".',
      choices: null,
      answer: 'A microkernel keeps only essential OS functions (IPC and basic scheduling) in privileged kernel mode. All other services — device drivers, file systems, virtual memory management, windowing, and security — run as isolated user-mode server processes.',
      figure: null,
    },

    // ==================== FILL IN THE BLANK ====================
    {
      type: 'fill',
      question: 'In paging, a virtual address consists of a __________ and an offset within that unit.',
      choices: null,
      answer: 'page number',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The __________ is the average time between a system starting operation and its first failure.',
      choices: null,
      answer: 'Mean Time To Failure (MTTF)',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A __________ fault is not present all the time and can be either transient or intermittent.',
      choices: null,
      answer: 'temporary',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The principal objective of time-sharing systems is to minimize __________ .',
      choices: null,
      answer: 'response time',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In the hierarchical OS model, level __________ handles interrupts with operations such as invoke, mask, unmask, and retry.',
      choices: null,
      answer: '4',
      figure: null,
    },
    {
      type: 'fill',
      question: 'SVR4 was developed jointly by AT&T and __________ .',
      choices: null,
      answer: 'Sun Microsystems',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The __________ in Android\'s Application Framework manages the lifecycle of application activities.',
      choices: null,
      answer: 'Activity Manager',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Linux uses a modular __________ kernel design, where the core runs as a single process but is structured using loadable modules.',
      choices: null,
      answer: 'monolithic',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The CTSS (Compatible Time-Sharing System) was developed at MIT and preempted users every __________ seconds.',
      choices: null,
      answer: '0.2',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The __________ is the hardware unit interposed between the processor and memory that translates virtual addresses to physical addresses.',
      choices: null,
      answer: 'MMU (Memory Management Unit)',
      figure: null,
    },
  ];

  const LECTURE = 2;
  const SOURCE = 'student';
  window.ALL_QUESTIONS.push(...lec02_student.map(q => ({ ...q, lecture: LECTURE, source: SOURCE })));
})();
