// ===== LECTURE 04: Processes and Threads — STUDENT =====
// Student-added questions only. Testbank questions are in (js/testbank/lec04.js)
// See GUIDE.md for how to add/edit questions.

if (typeof window.ALL_QUESTIONS === 'undefined') {
  window.ALL_QUESTIONS = [];
}

(function () {
  const lec04_student = [

    // ==================== TRUE / FALSE ====================
    {
      type: 'tf',
      question: 'A thread typically comprises a thread ID, a program counter, a register set, an execution stack, and per-thread static storage for local variables.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'These five elements are the standard components that define a thread\'s individual execution state.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In a pure ULT strategy, a multithreaded application can fully exploit multiprocessing because the kernel assigns each thread to a separate processor.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'In pure ULT, the kernel sees only one process and assigns it to one processor at a time, so multiple processors cannot be exploited.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'One advantage of ULTs over KLTs is that thread switching does not require a mode switch to the kernel.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'ULT context switches are handled entirely in user space by the thread library, with no kernel involvement.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'When a ULT makes a blocking system call, only that specific thread blocks while the other ULTs in the process continue to run.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'In a pure ULT approach, a blocking system call blocks the entire process (all ULTs within it), since the kernel sees only the process.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'With KLTs, if one thread in a process blocks, the kernel can schedule another thread from the same process to run.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'This is a key KLT advantage — the kernel manages individual threads and can run others from the same process if one blocks.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Jacketing converts a blocking system call into a non-blocking one, allowing other ULTs to continue executing.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'Jacketing is a ULT workaround that checks in advance whether a system call would block and uses async I/O if so.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In a 1:1 thread-to-process relationship, multiple threads share the same address space within one process.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'In a 1:1 relationship, each thread of execution is a unique process with its own address space — the traditional UNIX model.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Amdahl\'s Law states that if 40% of an application is serial, the maximum speedup achievable with unlimited processors is 2.5×.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'As N → ∞, speedup → 1/S = 1/0.4 = 2.5×. The serial fraction becomes the bottleneck.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In Linux, there is a strict kernel-level distinction between threads and processes.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Linux does not strictly distinguish between threads and processes at the kernel level; user-level threads are mapped into kernel-level processes (tasks).',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Android applications run in a shared process environment where multiple apps share the same virtual machine.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Each Android application runs in its own dedicated process and virtual machine (sandbox model), isolating it from other apps.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'A Windows fiber is a unit of execution that must be manually scheduled by the application, not by the OS scheduler.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'Unlike threads, fibers are cooperatively scheduled by the application — they do not preempt each other.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In Mac OS X Grand Central Dispatch (GCD), developers must manually manage which thread executes each block of work.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'GCD abstracts thread management — developers submit blocks to queues and the runtime assigns them to available threads/cores automatically.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'MS-DOS is an example of an operating system that uses a single-threaded approach (one thread per process).',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'MS-DOS does not recognize the thread concept and runs a single thread of execution per process.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Linux\'s clone() system call can create a new process that shares resources such as files, signals, and virtual memory with the parent.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'clone() is flexible — by passing appropriate flags, the new task can share the parent\'s address space, file descriptors, and signal handlers, effectively creating a thread.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'The Solaris combined ULT/KLT approach maps user-level threads onto a fixed, unchangeable number of kernel-level threads.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'In Solaris, the programmer can adjust the number of KLTs (LWPs) to match the application and processor configuration — it is not fixed.',
      figure: null,
    },

    // ==================== MULTIPLE CHOICE ====================
    {
      type: 'mcq',
      question: 'In the context of processes and threads, which is the "unit of resource ownership"?',
      choices: [
        'Thread',
        'Lightweight process',
        'Process (task)',
        'Fiber',
      ],
      answer: 2,
      hint: 'The process (or task) owns resources such as address space, files, and I/O channels. The thread is the unit of dispatching/execution.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'According to Amdahl\'s Law, what is the theoretical maximum speedup if 25% of an application is inherently serial?',
      choices: [
        '2×',
        '4×',
        '8×',
        'Unlimited',
      ],
      answer: 1,
      hint: 'Speedup max = 1/S = 1/0.25 = 4×. The serial fraction caps the speedup regardless of how many processors are added.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which thread-to-process relationship model allows a thread to migrate from one process address space to another?',
      choices: [
        '1:1',
        'M:1',
        '1:M',
        'M:N',
      ],
      answer: 2,
      hint: 'The 1:M model is used in distributed/mobility-oriented systems (e.g., Clouds, Emerald) where a thread can move between address spaces.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which thread-to-process model is used by traditional UNIX implementations, where each thread of execution is a unique process?',
      choices: [
        'M:1',
        '1:1',
        '1:M',
        'M:N',
      ],
      answer: 1,
      hint: 'Traditional UNIX uses 1:1 — each thread of execution corresponds to a unique process with its own address space.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'In the performance latency comparison, which thread implementation showed the lowest latency for the "Null Fork" operation?',
      choices: [
        'Kernel-Level Threads',
        'Processes',
        'User-Level Threads',
        'Fibers',
      ],
      answer: 2,
      hint: 'ULTs had ~34 μs for Null Fork vs ~948 μs for KLTs and ~11,300 μs for processes — orders of magnitude faster.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which Windows mechanism allows groups of processes to be managed as a single unit?',
      choices: [
        'Thread pool',
        'Job object',
        'Fiber',
        'User-mode scheduling (UMS)',
      ],
      answer: 1,
      hint: 'A job object in Windows groups multiple processes together so resource limits and control operations can be applied collectively.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which of the following is NOT an advantage of Kernel-Level Threads over User-Level Threads?',
      choices: [
        'The kernel can schedule threads from the same process on multiple processors simultaneously',
        'If one thread blocks, the kernel can run another thread from the same process',
        'Thread switching requires no mode switch to the kernel',
        'Kernel routines themselves can be multithreaded',
      ],
      answer: 2,
      hint: 'Requiring a mode switch to the kernel is the main DISADVANTAGE of KLTs. The other three are KLT advantages.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which Linux system call creates a new task that can optionally share files, signals, and virtual memory with the parent?',
      choices: [
        'fork()',
        'exec()',
        'spawn()',
        'clone()',
      ],
      answer: 3,
      hint: 'clone() is the flexible Linux system call that allows fine-grained control over what the new task shares with the parent, enabling thread-like behavior.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which of the four Android component types is responsible for responding to system-wide broadcast announcements?',
      choices: [
        'Activities',
        'Services',
        'Content providers',
        'Broadcast receivers',
      ],
      answer: 3,
      hint: 'Broadcast receivers listen for system-wide events (e.g., low battery, incoming call) and respond accordingly.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'What does Grand Central Dispatch (GCD) in Mac OS X use to represent self-contained units of work?',
      choices: [
        'Threads',
        'Fibers',
        'Blocks',
        'Tasks',
      ],
      answer: 2,
      hint: 'GCD uses "blocks" — anonymous functions/closures submitted to dispatch queues — as the fundamental units of work.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which Windows thread attribute indicates how many times the thread has been suspended without a corresponding resume?',
      choices: [
        'Alert status',
        'Suspension count',
        'Dynamic priority',
        'Impersonation token',
      ],
      answer: 1,
      hint: 'The suspension count tracks pending suspensions; the thread can only run again once the count reaches zero.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'In POSIX Pthreads, which function is used to yield the processor to another thread voluntarily?',
      choices: [
        'pthread_exit()',
        'pthread_join()',
        'pthread_yield()',
        'pthread_cond_wait()',
      ],
      answer: 2,
      hint: 'pthread_yield() causes the calling thread to relinquish the CPU, allowing other threads to run.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which of the following BEST describes a user-mode scheduling (UMS) in Windows?',
      choices: [
        'A kernel mechanism to preemptively schedule threads across all processors',
        'A lightweight application-level mechanism that lets applications schedule their own threads',
        'A scheduling policy where threads are assigned static priorities',
        'A hardware-assisted scheduling unit in the CPU',
      ],
      answer: 1,
      hint: 'UMS allows applications to manage their own thread scheduling in user mode, avoiding frequent kernel transitions.',
      figure: null,
    },

    // ==================== LIST ====================
    {
      type: 'list',
      question: 'List the five components that a thread typically comprises.',
      choices: null,
      answer: [
        'A thread ID',
        'A program counter',
        'A register set',
        'An execution stack',
        'Per-thread static storage for local variables',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the four thread operations that cause a change in thread state.',
      choices: null,
      answer: [
        'Spawn — create a new thread with its own register context and stack',
        'Block — wait for an event; save registers, PC, and stack pointer',
        'Unblock — event occurred; move thread to Ready state',
        'Finish — thread completed; deallocate register context and stack',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List three advantages of User-Level Threads (ULTs) over Kernel-Level Threads (KLTs).',
      choices: null,
      answer: [
        'Thread switching does not require kernel mode privileges (no mode switch overhead)',
        'Scheduling can be application-specific',
        'ULTs can run on any OS via a user-level thread library',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List two disadvantages of User-Level Threads (ULTs).',
      choices: null,
      answer: [
        'A blocking system call blocks the entire process (all ULTs within it)',
        'A pure ULT application cannot exploit multiprocessing — the kernel assigns one processor to the entire process',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List three advantages of Kernel-Level Threads (KLTs) over User-Level Threads (ULTs).',
      choices: null,
      answer: [
        'The kernel can schedule multiple threads from the same process on multiple processors simultaneously',
        'If one thread blocks, the kernel can schedule another thread from the same process',
        'Kernel routines themselves can be multithreaded',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the four thread-to-process relationship models and give one example OS for each.',
      choices: null,
      answer: [
        '1:1 — Each thread is a unique process (Traditional UNIX)',
        'M:1 — Multiple threads share one process address space (Windows NT, Solaris, Linux)',
        '1:M — A thread can migrate between process address spaces (Clouds, Emerald)',
        'M:N — Combines M:1 and 1:M (TRIX)',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the four component types that make up an Android application.',
      choices: null,
      answer: [
        'Activities — provide screens for user interaction',
        'Services — perform background operations',
        'Content providers — interface to shared application data',
        'Broadcast receivers — respond to system-wide broadcast events',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the four key benefits of using threads over processes.',
      choices: null,
      answer: [
        'Less time to create a new thread than a new process',
        'Less time to terminate a thread than a process',
        'Switching between threads takes less time than switching between processes',
        'Threads communicate via shared memory without kernel involvement (more efficient)',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List six Linux namespace types.',
      choices: null,
      answer: [
        'mnt (mount)',
        'pid (process IDs)',
        'net (network)',
        'ipc (inter-process communication)',
        'uts (hostname/domain name)',
        'user (user and group IDs)',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List five fields stored in a Linux task_struct.',
      choices: null,
      answer: [
        'State (execution state)',
        'Scheduling information (priority, policy)',
        'Identifiers (PID)',
        'Links to parent/sibling/children processes',
        'Times and timers (creation time, CPU time consumed)',
      ],
      figure: null,
    },

    // ==================== DEFINE ====================
    {
      type: 'define',
      question: 'Define "jacketing" in the context of User-Level Threads.',
      choices: null,
      answer: 'Jacketing is a technique used to work around the blocking-system-call problem of ULTs. It converts a blocking system call into a non-blocking one: before invoking the OS, the jacket code checks whether the I/O device is ready; if not, it uses asynchronous I/O so other ULTs can continue running.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "Amdahl\'s Law" and state its formula.',
      choices: null,
      answer: 'Amdahl\'s Law states that the speedup of a program using multiple processors is limited by the fraction of the program that must execute serially. Formula: Speedup = 1 / (S + (1 - S) / N), where S is the serial fraction (0–1) and N is the number of processors. As N → ∞, speedup approaches 1/S.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define a "fiber" in the context of Windows thread management.',
      choices: null,
      answer: 'A fiber is a unit of execution in Windows that must be manually scheduled by the application — the OS does not preemptively switch between fibers. This is in contrast to threads, which are preemptively scheduled by the kernel.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "Grand Central Dispatch (GCD)" as used in Mac OS X.',
      choices: null,
      answer: 'Grand Central Dispatch (GCD) is a concurrency framework in Mac OS X that provides a pool of available threads and a queue-based mechanism for dispatching self-contained units of work called "blocks." Developers submit blocks to FIFO dispatch queues and the runtime automatically maps them to available threads and CPU cores.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "Linux namespaces" and explain their purpose.',
      choices: null,
      answer: 'Linux namespaces are kernel features that give a process a different, isolated view of system resources than other processes. Each namespace type isolates a specific resource (e.g., mnt for mount points, pid for process IDs, net for network stack, ipc, uts, user). They are the foundation for container technologies like Docker.',
      figure: null,
    },

    // ==================== FILL IN THE BLANK ====================
    {
      type: 'fill',
      question: 'According to Amdahl\'s Law, if the serial fraction S = 0.5, the maximum speedup with unlimited processors is __________ .',
      choices: null,
      answer: '2×',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In the M:1 thread-to-process model, multiple threads share a single __________ .',
      choices: null,
      answer: 'process address space',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The technique of converting a blocking system call into a non-blocking call in a ULT environment is called __________ .',
      choices: null,
      answer: 'jacketing',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A Windows __________ allows groups of processes to be managed and controlled as a single unit.',
      choices: null,
      answer: 'job object',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In Linux, the __________ system call can create a new process that shares virtual memory, files, and signals with the parent, effectively creating a thread.',
      choices: null,
      answer: 'clone()',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Each Android application runs in its own dedicated process and __________ , enforcing isolation between applications.',
      choices: null,
      answer: 'virtual machine',
      figure: null,
    },
    {
      type: 'fill',
      question: 'POSIX Threads is an IEEE API standard commonly implemented as __________ .',
      choices: null,
      answer: 'pthreads',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Windows supports __________ affinity (default) where the dispatcher tries to reuse the processor a thread last ran on, taking advantage of hardware caches.',
      choices: null,
      answer: 'soft',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In Solaris, user-level threads are mapped onto a set of kernel-level threads called __________ .',
      choices: null,
      answer: 'LWPs (Lightweight Processes)',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Mac OS X Grand Central Dispatch schedules self-contained units of work called __________ using FIFO queues.',
      choices: null,
      answer: 'blocks',
      figure: null,
    },
  ];

  const LECTURE = 4;
  const SOURCE = 'student';
  window.ALL_QUESTIONS.push(...lec04_student.map(q => ({ ...q, lecture: LECTURE, source: SOURCE })));
})();
