// ===== LECTURE 03: Process Description and Control — STUDENT =====

if (typeof window.ALL_QUESTIONS === 'undefined') {
  window.ALL_QUESTIONS = [];
}

(function () {
  const lec03 = [

    // ==================== TRUE / FALSE ====================

    {
      type: 'tf',
      question: 'A process is defined as a program in execution, and it can be uniquely characterized at any point by its identifier, state, program counter, and associated resources.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'These are all exactly the elements used to characterize a running process at any given moment.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In a two-state process model, a process can only be in one of two states: Running or Blocked.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The two states in the two-state model are Running and Not Running (not Blocked). "Blocked" is a refinement introduced in the five-state model.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'When a process is created via process spawning, the creating process is called the parent process and the created process is called the child process.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'In the five-state model, a process in the New state has its program code already loaded into main memory.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'In the New state, the OS has created a PCB and prepared the process but has NOT yet loaded the program code into main memory. The code remains in secondary storage.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'A process in the Ready/Suspend state is in secondary memory but is available for execution as soon as it is loaded into main memory.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'A mode switch and a process switch are the same operation; both require saving and restoring the full process context.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'A mode switch only saves/restores processor state and changes privilege level (user ↔ kernel). A process switch additionally updates the PCB, moves the process to a queue, and loads a new process — it is a much heavier operation.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'The process control block contains sufficient information to interrupt a running process and later resume execution as if the interruption had not occurred.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'In round-robin scheduling, each process is given an unlimited amount of time to execute before the next process is dispatched.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Round-robin gives each process a fixed time slice. When the time slice expires, the process is returned to the ready queue and the next process runs.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'The OS maintains four types of tables to manage the system: memory, I/O, file, and process tables.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'A trap is an interrupt caused by an event external to and independent of the currently running process.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'A trap is caused by an error or exception generated WITHIN the currently running process (e.g., illegal memory access). An external event causes a regular interrupt.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In UNIX SVR4, a process running in kernel mode can be preempted at any time by a higher-priority process.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'In UNIX SVR4, a process running in kernel mode cannot be preempted. Preemption can only occur when a process is about to transition from kernel mode back to user mode.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'The process image is the complete collection of program code, data, stack, and process control block associated with a process.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'In UNIX, the fork() system call creates a new process by making a copy of the parent process image (except shared memory).',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'The program status word (PSW) is a register that contains only the program counter value.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The PSW (e.g., x86 EFLAGS) contains status information such as condition codes, interrupt flags, and execution mode bits — not just the program counter.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'When an OS uses swapping to free main memory, it moves a process (or part of it) from main memory to disk.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },

    // ==================== MULTIPLE CHOICE ====================

    {
      type: 'mcq',
      question: 'Which of the following is NOT one of the four events that commonly lead to the creation of a new process?',
      choices: [
        'New batch job submission',
        'Interactive user log-on',
        'Process requesting an I/O operation',
        'An existing process spawning a child process',
      ],
      answer: 2,
      hint: 'I/O requests block a process but do not create a new one. The four creation events are: new batch job, interactive log-on, OS creating a service process, and process spawning.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'What is the primary problem with the single-queue two-state model when some processes are blocked?',
      choices: [
        'The queue can only hold one process at a time',
        'The dispatcher must scan the entire queue to find a non-blocked process',
        'Blocked processes are deleted from the queue immediately',
        'The OS cannot distinguish between running and not-running processes',
      ],
      answer: 1,
      hint: 'With a single queue mixing ready and blocked processes, the dispatcher cannot simply pick the front process — it must scan the whole queue to find one that is actually ready to run.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which state transition in the five-state model occurs when the OS selects a process from the ready queue to execute?',
      choices: [
        'New → Ready',
        'Ready → Running',
        'Running → Blocked',
        'Blocked → Ready',
      ],
      answer: 1,
      hint: 'The dispatcher (scheduler) selects a process from the Ready queue and moves it to the Running state.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which of the following best describes the Blocked/Suspend state?',
      choices: [
        'The process is in main memory and waiting for an event',
        'The process is in secondary memory and ready to run',
        'The process is in secondary memory and waiting for an event',
        'The process is in main memory and currently executing',
      ],
      answer: 2,
      hint: 'Blocked/Suspend = out of main memory (on disk) AND still waiting for an event. Contrast with Ready/Suspend, which is also on disk but NOT waiting for an event.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which of the following is the MOST important data structure in an operating system?',
      choices: [
        'Memory table',
        'File table',
        'Process control block',
        'I/O table',
      ],
      answer: 2,
      hint: 'The PCB is described as the most important OS data structure — it contains all information needed to manage a process and is accessed by virtually every OS module.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'In the context of process control block information, which category includes the program counter, condition codes, and status information?',
      choices: [
        'Process identification',
        'Processor state information',
        'Process control information',
        'Memory management information',
      ],
      answer: 1,
      hint: 'Processor state information captures the state of the CPU registers at any point, including the program counter, condition codes, and PSW — all needed to resume a process after interruption.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'What triggers a transition from Running to Blocked state in the five-state process model?',
      choices: [
        'The process\'s time slice expires',
        'A higher-priority process becomes ready',
        'The process requests a resource or I/O that is not immediately available',
        'The process completes execution',
      ],
      answer: 2,
      hint: 'A process moves to Blocked when it must wait for something (I/O completion, a resource, a message). Time slice expiry leads to Ready, and completion leads to Exit.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which mode of execution allows the software to execute privileged instructions and access all memory regions?',
      choices: [
        'User mode',
        'Kernel mode',
        'Protected mode',
        'Supervisor mode',
      ],
      answer: 1,
      hint: 'Kernel mode (also called system mode or control mode) grants full access to all processor instructions and memory. User mode is the less-privileged mode.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'What is a "time slice" in the context of process scheduling?',
      choices: [
        'The total time a process spends in the blocked state',
        'The maximum amount of time a process can execute before being interrupted',
        'The time it takes to perform a process switch',
        'The minimum amount of CPU time guaranteed to each process',
      ],
      answer: 1,
      hint: 'A time slice (or quantum) is the maximum continuous execution time allowed before the OS intervenes. When it expires, a clock interrupt triggers a potential process switch.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which of the following is a reason for suspending a process OTHER than freeing memory (swapping)?',
      choices: [
        'The process has completed normally',
        'The process caused a bounds violation',
        'An operator suspects the process is causing a problem',
        'The process\'s time slice has expired',
      ],
      answer: 2,
      hint: 'Reasons for suspension include: swapping, OS suspicion of a problem, user debugging request, timing (periodic processes), and parent process request.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'What happens during a full process switch (as opposed to just a mode switch)?',
      choices: [
        'Only the program counter is saved',
        'The privilege level changes but the currently running process continues',
        'The OS saves context, updates PCBs, selects a new process, and restores that process\'s context',
        'The process is moved from main memory to disk',
      ],
      answer: 2,
      hint: 'A full process switch involves: saving CPU context, updating current PCB, moving it to a queue, selecting a new process, updating its PCB to Running, and restoring its context.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'In UNIX SVR4, the "Zombie" state means:',
      choices: [
        'The process is running with excessively high CPU usage',
        'The process is sleeping and cannot be woken up',
        'The process no longer exists but leaves a record for its parent to collect',
        'The process is swapped out and awaiting an event',
      ],
      answer: 2,
      hint: 'A Zombie process has completed execution but its entry is kept in the process table until the parent process reads its exit status via wait().',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which approach to OS execution runs the kernel entirely outside of any user process, in its own privileged memory region?',
      choices: [
        'Execution within user processes',
        'Process-based OS',
        'Nonprocess kernel',
        'Microkernel architecture',
      ],
      answer: 2,
      hint: 'The nonprocess kernel (separate kernel) approach keeps OS code outside user processes. When a user process is interrupted, control transfers to the kernel\'s own memory region.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Which element of the UNIX process image contains process control information that is always accessible to the OS kernel, even when the process is not running?',
      choices: [
        'U (user) area',
        'Kernel stack',
        'Process table entry',
        'Per-process region table',
      ],
      answer: 2,
      hint: 'The process table entry must always be accessible to the OS (e.g., for scheduling). The U area is only needed when executing in the context of that specific process.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A process switches from Blocked to Blocked/Suspend when:',
      choices: [
        'It finishes waiting for its event and is ready to run',
        'There are no ready processes and the OS needs to free main memory',
        'Its time slice expires while it is waiting',
        'A parent process requests its termination',
      ],
      answer: 1,
      hint: 'The OS performs a Blocked → Blocked/Suspend transition by swapping out a blocked process to free main memory, usually when there are no ready processes left in memory.',
      figure: null,
    },

    // ==================== FILL IN THE BLANK ====================

    {
      type: 'fill',
      question: 'The sequence of instructions that execute for a given process, used to characterize its behavior, is called a __________.',
      choices: null,
      answer: 'trace',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The five states in the five-state process model are: New, Ready, Running, __________, and Exit.',
      choices: null,
      answer: 'Blocked',
      figure: null,
    },
    {
      type: 'fill',
      question: 'When an OS creates a process at the explicit request of another process, this action is called __________.',
      choices: null,
      answer: 'process spawning',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The three general categories of information stored in a process control block are: process identification, processor state information, and __________.',
      choices: null,
      answer: 'process control information',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In kernel mode, the software has complete control of the processor and all instructions. The less-privileged counterpart to kernel mode is called __________ mode.',
      choices: null,
      answer: 'user',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A __________ is an interrupt-like event caused by an error or exception condition generated within the currently running process itself.',
      choices: null,
      answer: 'trap',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The portion of the OS responsible for selecting the next process to run and giving it control of the processor is called the __________.',
      choices: null,
      answer: 'dispatcher',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In the four-state extended model with suspending, a process that is in main memory and awaiting an event is in the __________ state.',
      choices: null,
      answer: 'Blocked',
      figure: null,
    },
    {
      type: 'fill',
      question: 'UNIX process creation is performed using the kernel system call __________().',
      choices: null,
      answer: 'fork',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The x86 register that serves as the program status word (PSW), containing condition codes and system flags, is called the __________ register.',
      choices: null,
      answer: 'EFLAGS',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In UNIX SVR4, a total of __________ process states are recognized.',
      choices: null,
      answer: '9',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The collection of a process\'s program, data, stack, and attributes (PCB) is referred to as the process __________.',
      choices: null,
      answer: 'image',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In UNIX, the first process created at boot time (the swapper) is called process __________, and it spawns process 1 (the init process).',
      choices: null,
      answer: '0',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A __________ is the maximum amount of time a process is allowed to run continuously before the OS may preempt it.',
      choices: null,
      answer: 'time slice',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The OS table type that records the existence of files, their location on secondary memory, and their current status is called the __________ table.',
      choices: null,
      answer: 'file',
      figure: null,
    },

    // ==================== LIST ====================

    {
      type: 'list',
      question: 'List the FOUR common reasons (events) that lead to the creation of a new process.',
      choices: null,
      answer: [
        'New batch job submission',
        'Interactive user log-on',
        'OS creating a process to provide a service (e.g., print management)',
        'An existing process spawns a child process (process spawning)',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the FIVE states in the five-state process model and give a one-line description of each.',
      choices: null,
      answer: [
        'New – Process just created; PCB created but not yet admitted to execution pool',
        'Ready – Process in main memory, prepared to execute when assigned the CPU',
        'Running – Process currently being executed by the processor',
        'Blocked – Process in main memory waiting for an event (e.g., I/O completion)',
        'Exit – Process released from the execution pool (completed or aborted)',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the FOUR states in the extended model that includes suspended processes (with swapping).',
      choices: null,
      answer: [
        'Ready – In main memory, available for execution',
        'Blocked – In main memory, waiting for an event',
        'Ready/Suspend – In secondary memory, ready to run once loaded into main memory',
        'Blocked/Suspend – In secondary memory, still waiting for an event',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the three categories of information stored in a Process Control Block (PCB).',
      choices: null,
      answer: [
        'Process identification (unique ID, parent ID, user ID)',
        'Processor state information (registers, program counter, PSW, stack pointers)',
        'Process control information (scheduling state, priority, data structuring, IPC info, privileges, memory management, resource ownership)',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the SEVEN steps involved in a full process switch (change of process state).',
      choices: null,
      answer: [
        '1. Save the context of the processor (program counter and registers)',
        '2. Update the PCB of the currently running process (change state, update accounting)',
        '3. Move the current process\'s PCB to the appropriate queue (Ready, Blocked, etc.)',
        '4. Select another process for execution',
        '5. Update the PCB of the selected process (change state to Running)',
        '6. Update memory management data structures if needed',
        '7. Restore the context of the selected process (load its registers and program counter)',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List at least FOUR reasons why a process might be suspended.',
      choices: null,
      answer: [
        'Swapping – OS needs to free main memory for another process',
        'Other OS reason – OS suspects the process of causing a problem or it is a background utility',
        'Interactive user request – User wants to debug or pause the program',
        'Timing – Process is periodic and suspended between activations',
        'Parent process request – Parent wishes to examine or coordinate a descendant',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the FOUR types of OS control tables and briefly state what each manages.',
      choices: null,
      answer: [
        'Memory tables – Track allocation of main and secondary memory to processes',
        'I/O tables – Manage I/O devices and channels; track I/O operation status',
        'File tables – Record file existence, location, status, and attributes',
        'Process tables – Manage process state, location, and attributes (via PCBs)',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the three approaches to OS execution described in the chapter.',
      choices: null,
      answer: [
        'Nonprocess kernel – OS kernel executes outside any user process, in its own privileged region',
        'Execution within user processes – OS routines run within the context of the current user process (mode switch, not process switch)',
        'Process-based OS – Major OS functions are organized as separate kernel-mode processes',
      ],
      figure: null,
    },
    {
      type: 'list',
      question: 'List the nine process states recognized by UNIX SVR4.',
      choices: null,
      answer: [
        'User Running',
        'Kernel Running',
        'Ready to Run, in Memory',
        'Asleep in Memory (blocked)',
        'Ready to Run, Swapped',
        'Sleeping, Swapped (blocked)',
        'Preempted',
        'Created',
        'Zombie',
      ],
      figure: null,
    },

    // ==================== DEFINE ====================

    {
      type: 'define',
      question: 'Define "process" as used in operating systems.',
      choices: null,
      answer: 'A process is a program in execution — a unit of activity characterized by the execution of a sequence of instructions, a current state, and an associated set of system resources. It consists of program code, associated data, and a process control block.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "process spawning" and identify the two processes involved.',
      choices: null,
      answer: 'Process spawning occurs when an existing process explicitly requests the OS to create a new process. The creating process is called the parent process, and the newly created process is called the child process.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "swapping" and explain why it can improve system performance.',
      choices: null,
      answer: 'Swapping is the operation of moving part or all of a process from main memory to secondary storage (disk). It improves performance by freeing main memory so that other processes can be loaded and executed, preventing the CPU from being idle when all in-memory processes are blocked. Although it is an I/O operation, disk I/O is fast enough to make it beneficial in most cases.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "mode switch" and explain how it differs from a "process switch".',
      choices: null,
      answer: 'A mode switch is a change in the processor\'s privilege level (user mode ↔ kernel mode), saving only the processor state information. Execution may continue in the same process. A process switch also changes the active process: it saves the full context of the current process, moves it to a queue, selects a new process, and restores that new process\'s context. A process switch is therefore a much heavier operation than a mode switch.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "process control block (PCB)" and explain its role in supporting multiprogramming.',
      choices: null,
      answer: 'The process control block (PCB) is an OS data structure that stores all information needed to manage a process: its identifier, state, processor registers, scheduling priority, memory pointers, I/O status, and accounting data. It is the most important OS data structure. By saving and restoring the PCB, the OS can suspend any running process and later resume it exactly where it left off, enabling multiple processes to share the CPU (multiprogramming).',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "preemption" in the context of process scheduling.',
      choices: null,
      answer: 'Preemption is the reclaiming of the CPU from a currently running process before that process has voluntarily relinquished it. This typically occurs when a higher-priority process becomes ready, or when the running process\'s time slice expires. The preempted process moves from Running to Ready state.',
      figure: null,
    },
    {
      type: 'define',
      question: 'Define "trace" of a process and explain how interleaved traces model multiprogramming.',
      choices: null,
      answer: 'A trace of a process is the sequence of memory addresses (instructions) executed during that process\'s lifetime. By listing the interleaved traces of multiple processes — showing how the processor alternates among them (including dispatcher execution) — we can model the behavior of multiprogramming: multiple processes appear to progress concurrently even on a single processor.',
      figure: null,
    },
  ];

  const LECTURE = 3;
  const SOURCE = 'student';
  window.ALL_QUESTIONS.push(...lec03.map(q => ({ ...q, lecture: LECTURE, source: SOURCE })));
})();
