// ===== LECTURE 04: Threads — TESTBANK =====
// Source: Operating Systems Internals and Design Principles, 8th Edition
// Testbank questions only. For student-added questions see js/student/lec04.js
// See GUIDE.md for how to add/edit questions.

if (typeof window.ALL_QUESTIONS === 'undefined') {
  window.ALL_QUESTIONS = [];
}

(function () {
  const lec04 = [
    // ==================== TRUE / FALSE ====================
    {
      type: 'tf',
      question: 'The OS performs a protection function to prevent unwanted interference between processes with respect to resources.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'Windows process design is driven by the need to provide support for a variety of OS environments.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'The unit of dispatching is usually referred to as a process or task.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The unit of dispatching is usually referred to as a thread or lightweight process, not a process or task.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In a multithreaded environment there are separate stacks for each thread, as well as a separate control block for each thread.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'Each thread has its own stack and thread control block, but threads within the same process share the address space and resources.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'It takes less time to terminate a process than a thread.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Threads are lighter weight than processes. It takes less time to create and terminate a thread than a process.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'If there is an application or function that should be implemented as a set of related units of execution, it is far more efficient to do so as a collection of separate processes rather than a collection of threads.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Threads within a single process share resources and are much more efficient to create, manage, and switch between than separate processes.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'An example of an application that could make use of threads is a file server.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'A file server can handle multiple simultaneous client requests using separate threads for each request.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Termination of a process does not terminate all threads within that process.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'When a process is terminated, all threads within that process are also terminated since they share the process address space.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'If a process is swapped out, all of its threads are necessarily swapped out because they all share the address space of the process.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'On a uniprocessor, multiprogramming does not enable the interleaving of multiple threads within multiple processes.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Multiprogramming on a uniprocessor does enable interleaving of threads by rapidly switching between them.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Any alteration of a resource by one thread affects the environment of the other threads in the same process.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'Threads within the same process share resources, so a change by one thread is visible to all others.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'In a pure ULT facility, all of the work of thread management is done by the application, and the kernel is not aware of the existence of threads.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'As a default, the kernel dispatcher uses the policy of hard affinity in assigning threads to processors.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The default policy is soft affinity, where the OS tries to keep a thread on the same processor but may move it if needed. Hard affinity restricts a thread to specific processors and must be explicitly set.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Windows is an example of a kernel-level thread approach.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'The potential performance benefits of a multicore organization depend on the ability to effectively exploit the parallel resources available to the application.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },

    // ==================== MULTIPLE CHOICE ====================
    {
      type: 'mcq',
      question: 'The traditional approach of a single thread of execution per process, in which the concept of a thread is not recognized, is referred to as a __________ .',
      choices: [
        'task',
        'resource',
        'single-threaded approach',
        'lightweight process',
      ],
      answer: 2,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The idea of having a many-to-many relationship between threads and processes has been explored in the experimental operating system _________ .',
      choices: [
        'VISTA',
        'TRIX',
        'SOLARIS',
        'LEOPARD',
      ],
      answer: 1,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: 'In a multithreaded environment, a __________ is defined as the unit of resource allocation and a unit of protection.',
      choices: [
        'strand',
        'process',
        'string',
        'trace',
      ],
      answer: 1,
      hint: 'A process owns resources and provides protection boundaries. Threads within a process share those resources.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The principal disadvantage of the _________ approach is that the transfer of control from one thread to another within the same process requires a mode switch to the kernel.',
      choices: [
        'KLT',
        'LWP',
        'VAX',
        'ULT',
      ],
      answer: 0,
      hint: 'With Kernel-Level Threads (KLT), every thread operation requires a mode switch to the kernel, which adds overhead.',
      figure: null,
    },
    {
      type: 'mcq',
      question: '_________ is a good example of an OS using a combined ULT/KLT approach.',
      choices: [
        'TRIX',
        'Windows',
        'LINUX',
        'Solaris',
      ],
      answer: 3,
      hint: 'Solaris uses a combined approach with both user-level and kernel-level threads.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A _________ is a single execution path with an execution stack, processor state, and scheduling information.',
      choices: [
        'domain',
        'strand',
        'thread',
        'message',
      ],
      answer: 2,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: '__________ are characterized by the presence of many single-threaded processes.',
      choices: [
        'Multiprocess applications',
        'Java applications',
        'Multiinstance applications',
        'Multithreaded native applications',
      ],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A __________ is a dispatchable unit of work that executes sequentially and is interruptible so that the processor can turn to another thread.',
      choices: [
        'port',
        'process',
        'token',
        'thread',
      ],
      answer: 3,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A __________ is an entity corresponding to a user job or application that owns resources such as memory and open files.',
      choices: [
        'task',
        'process',
        'thread',
        'token',
      ],
      answer: 1,
      hint: 'A process is the unit of resource ownership. Threads within a process share those resources.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A ________ is a user-created unit of execution within a process.',
      choices: [
        'Kernel',
        'KLT',
        'lightweight process',
        'ULT',
      ],
      answer: 3,
      hint: 'User-Level Threads (ULTs) are created and managed by the application (user) without kernel involvement.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A Windows process must contain at least _________ thread(s) to execute.',
      choices: [
        'four',
        'three',
        'two',
        'one',
      ],
      answer: 3,
      hint: 'Every Windows process must have at least one thread to execute.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A thread enters the _________ state, after waiting, if it is ready to run but the resources are not available.',
      choices: [
        'Terminated',
        'Standby',
        'Transition',
        'Waiting',
      ],
      answer: 2,
      hint: 'The Transition state means the thread is ready to run but waiting for resources (e.g., its kernel stack is paged out).',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The _________ are the fundamental entities that can be scheduled and dispatched to run on one of the system processors.',
      choices: [
        'Processes',
        'Kernel threads',
        'LWPs',
        'ULTs',
      ],
      answer: 1,
      hint: 'Kernel threads are the entities that the OS scheduler dispatches to processors.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The __________ state is when the thread has terminated.',
      choices: [
        'ZOMBIE',
        'FREE',
        'STOP',
        'SLEEP',
      ],
      answer: 0,
      hint: 'In Linux/UNIX, a terminated process/thread enters the ZOMBIE state until its parent retrieves its exit status.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The blocked state in which the process is waiting for an event, such as the end of an I/O operation, the availability of a resource, or a signal from another process is the _________ state.',
      choices: [
        'Times and timers',
        'Uninterruptible',
        'Stopped',
        'Interruptible',
      ],
      answer: 3,
      hint: 'The Interruptible state means the process is blocked waiting for an event but can be awakened by a signal.',
      figure: null,
    },

    // ==================== FILL IN THE BLANK ====================
    {
      type: 'fill',
      question: 'The __________ is the collection of program, data, stack, and attributes defined in the process control block.',
      choices: null,
      answer: 'process image',
      figure: null,
    },
    {
      type: 'fill',
      question: '__________ refers to the ability of an OS to support multiple, concurrent paths of execution within a single process.',
      choices: null,
      answer: 'Multithreading',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The key states for a thread are: Running, _________, and Blocked.',
      choices: null,
      answer: 'Ready',
      figure: null,
    },
    {
      type: 'fill',
      question: 'There are four basic thread operations associated with a change in thread state: Block, Unblock, Finish, and _________ .',
      choices: null,
      answer: 'Spawn',
      figure: null,
    },
    {
      type: 'fill',
      question: 'There are two broad categories of thread implementation: user-level threads (ULTs) and _________ .',
      choices: null,
      answer: 'Kernel-level threads (KLTs)',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A way to overcome the problem of blocking threads is to use a technology referred to as __________ , which converts a blocking system call into a nonblocking system call.',
      choices: null,
      answer: 'jacketing',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A __________ is a static entity, consisting of an address space and ports through which messages may be sent and received.',
      choices: null,
      answer: 'domain',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Windows makes use of two types of process-related objects: processes and _________ .',
      choices: null,
      answer: 'threads',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The __________ Windows Process Object Attribute describes who created an object, who can gain access to or use the object, and who is denied access to the object.',
      choices: null,
      answer: 'security descriptor',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The six states of a Windows thread are: Ready, Standby, Running, Waiting, Transition, and _________ .',
      choices: null,
      answer: 'Terminated',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Most operating systems contain two fundamental forms of concurrent activity: processes and _________ .',
      choices: null,
      answer: 'interrupts',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A process or task in Linux is represented by a __________ data structure.',
      choices: null,
      answer: 'task_struct',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The Clouds operating system implements the concept of a thread as primarily an entity that can move among address spaces which represents the __________ Thread-to-Process relationship.',
      choices: null,
      answer: 'One-to-Many',
      figure: null,
    },
    {
      type: 'fill',
      question: 'It is necessary to __________ the activities of various threads so they do not interfere with each other or corrupt data structures.',
      choices: null,
      answer: 'synchronize',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The basic form of communication between processes or threads in a microkernel operating system is _________ .',
      choices: null,
      answer: 'messages',
      figure: null,
    },
  ];

  const LECTURE = 4;
  const SOURCE = 'testbank';
  window.ALL_QUESTIONS.push(...lec04.map(q => ({ ...q, lecture: LECTURE, source: SOURCE })));
})();
