// ===== CHAPTER 02: Operating System Overview =====
// Source: Operating Systems Internals and Design Principles, 8th Edition - Testbank
// See GUIDE.md for how to add/edit questions.

if (typeof window.ALL_QUESTIONS === 'undefined') {
  window.ALL_QUESTIONS = [];
}

(function () {
  const ch02 = [
    // ==================== TRUE / FALSE ====================
    {
      id: 'ch02_tf_001',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'An OS should be constructed in such a way as to permit the effective development, testing, and introduction of new system functions without interfering with service.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_tf_002',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'The OS masks the details of the hardware from the programmer and provides the programmer with a convenient interface for using the system.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_tf_003',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'The ABI gives a program access to the hardware resources and services available in a system through the user ISA.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The ABI (Application Binary Interface) provides access through system call interfaces, not directly through the user ISA.',
      figure: null,
    },
    {
      id: 'ch02_tf_004',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'The OS frequently relinquishes control and must depend on the processor to allow it to regain control.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'The OS gives up control when a user program runs and relies on interrupts and traps to regain control.',
      figure: null,
    },
    {
      id: 'ch02_tf_005',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'One of the driving forces in operating system evolution is advancement in the underlying hardware technology.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_tf_006',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'The processor itself is not a resource so the OS is not involved in determining how much of the processor time is devoted to the execution of a user program.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The processor is a key resource managed by the OS. The OS schedules and allocates processor time among programs.',
      figure: null,
    },
    {
      id: 'ch02_tf_007',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'A process consists of three components: an executable program, the associated data needed by the program, and the execution context of the program.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_tf_008',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'Uniprogramming typically provides better utilization of system resources than multiprogramming.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Multiprogramming keeps the CPU busy by switching between programs during I/O waits, providing much better resource utilization than uniprogramming.',
      figure: null,
    },
    {
      id: 'ch02_tf_009',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'A monolithic kernel is implemented as a single process with all elements sharing the same address space.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_tf_010',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'The user has direct access to the processor with a batch-processing type of OS.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'In batch processing, users submit jobs and the monitor controls access to the processor. Users do not interact directly with the processor.',
      figure: null,
    },
    {
      id: 'ch02_tf_011',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'Both batch processing and time-sharing use multiprogramming.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_tf_012',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'The phrase "control is passed to a job" means that the processor is now fetching and executing instructions from the monitor program.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'When control is passed to a job, the processor fetches and executes instructions from the user program, not from the monitor.',
      figure: null,
    },
    {
      id: 'ch02_tf_013',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'In a time-sharing system, a user\'s program is preempted at regular intervals, but due to relatively slow human reaction time this occurrence is usually transparent to the user.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_tf_014',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'The principle objective of Batch Multiprogramming is to minimize response time.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The principal objective of batch multiprogramming is to maximize processor use, not minimize response time. Minimizing response time is the objective of time-sharing.',
      figure: null,
    },
    {
      id: 'ch02_tf_015',
      chapter: 2,
      source: 'testbank',
      type: 'tf',
      question: 'Virtualization technology enables a single PC or server to simultaneously run multiple operating systems or multiple sessions of a single OS.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },

    // ==================== MULTIPLE CHOICE ====================
    {
      id: 'ch02_mcq_001',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'The __________ is the interface that is the boundary between hardware and software.',
      choices: [
        'ABI',
        'ISA',
        'IAS',
        'API',
      ],
      answer: 1,
      hint: 'The Instruction Set Architecture (ISA) defines the boundary between hardware and software.',
      figure: null,
    },
    {
      id: 'ch02_mcq_002',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'A(n) __________ is a set of resources for the movement, storage, and processing of data and for the control of these functions.',
      choices: [
        'architecture',
        'program',
        'computer',
        'application',
      ],
      answer: 2,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_mcq_003',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'The operating system\'s __________ refers to its inherent flexibility in permitting functional modifications to the system without interfering with service.',
      choices: [
        'efficiency',
        'ability to evolve',
        'controlled access',
        'convenience',
      ],
      answer: 1,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_mcq_004',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'Operating systems must evolve over time because:',
      choices: [
        'new hardware is designed and implemented in the computer system',
        'hardware must be replaced when it fails',
        'hardware is hierarchical',
        'users will only purchase software that has a current copyright date',
      ],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_mcq_005',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'A special type of programming language used to provide instructions to the monitor is __________ .',
      choices: [
        'FPL',
        'JCL',
        'DML',
        'SML',
      ],
      answer: 1,
      hint: 'JCL stands for Job Control Language, used to give instructions to the batch monitor.',
      figure: null,
    },
    {
      id: 'ch02_mcq_006',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'Hardware features desirable in a batch-processing operating system include memory protection, timer, privileged instructions, and __________ .',
      choices: [
        'clock cycles',
        'associated data',
        'interrupts',
        'kernels',
      ],
      answer: 2,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_mcq_007',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'A user program executes in a __________ , in which certain areas of memory are protected from the user\'s use, and in which certain instructions may not be executed.',
      choices: [
        'kernel mode',
        'user mode',
        'task mode',
        'batch mode',
      ],
      answer: 1,
      hint: 'In user mode, the program has restricted access to memory and cannot execute privileged instructions.',
      figure: null,
    },
    {
      id: 'ch02_mcq_008',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'Multiprogramming operating systems are fairly sophisticated compared to single-program or _________ systems.',
      choices: [
        'uniprogramming',
        'time-sharing',
        'multitasking',
        'memory management',
      ],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_mcq_009',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'One of the first time-sharing operating systems to be developed was the __________ .',
      choices: [
        'Compatible Time-Sharing System',
        'Real Time Transaction System',
        'Multiple-Access System',
        'Multiprogramming Operation System',
      ],
      answer: 0,
      hint: 'CTSS (Compatible Time-Sharing System) was developed at MIT and was one of the first time-sharing systems.',
      figure: null,
    },
    {
      id: 'ch02_mcq_010',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'The technique where a system clock generates interrupts, and at each clock interrupt the OS regains control and assigns the processor to another user, is __________ .',
      choices: [
        'time slicing',
        'multithreading',
        'round robin',
        'clock cycle',
      ],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_mcq_011',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'The __________ is the internal data by which the OS is able to supervise and control the process.',
      choices: [
        'executable program',
        'associated data',
        'nucleus',
        'execution context',
      ],
      answer: 3,
      hint: 'The execution context (or process state) contains all the information the OS needs to manage the process.',
      figure: null,
    },
    {
      id: 'ch02_mcq_012',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: '__________ is where the OS must prevent independent processes from interfering with each other\'s memory, both data and instructions.',
      choices: [
        'Support of modular programming',
        'Process isolation',
        'Automatic allocation and management',
        'Protection and access control',
      ],
      answer: 1,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_mcq_013',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: '__________ is concerned with the proper verification of the identity of users and the validity of messages or data.',
      choices: [
        'Availability',
        'Confidentiality',
        'Authenticity',
        'Data integrity',
      ],
      answer: 2,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_mcq_014',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'A common strategy to give each process in the queue some time in turn is referred to as a __________ technique.',
      choices: [
        'multithreading',
        'round-robin',
        'time slicing',
        'serial processing',
      ],
      answer: 1,
      hint: null,
      figure: null,
    },
    {
      id: 'ch02_mcq_015',
      chapter: 2,
      source: 'testbank',
      type: 'mcq',
      question: 'The key to the success of Linux has been its character as a free software package available under the auspice of the ___________ .',
      choices: [
        'World Wide Web Consortium',
        'Free Software Foundation',
        'Berkeley Software Distribution',
        'GNU Public License',
      ],
      answer: 1,
      hint: null,
      figure: null,
    },

    // ==================== FILL IN THE BLANK ====================
    {
      id: 'ch02_fill_001',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'An __________ is a program that controls the execution of application programs and acts as an interface between applications and the computer hardware.',
      choices: null,
      answer: 'operating system (OS)',
      figure: null,
    },
    {
      id: 'ch02_fill_002',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'The portion of the monitor that is always in main memory and available for execution is referred to as the _________ .',
      choices: null,
      answer: 'resident monitor',
      figure: null,
    },
    {
      id: 'ch02_fill_003',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: '__________ is a technique in which a process, executing an application, is divided into threads that can run concurrently.',
      choices: null,
      answer: 'Multithreading',
      figure: null,
    },
    {
      id: 'ch02_fill_004',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'Two major problems with early serial processing systems were scheduling and __________ .',
      choices: null,
      answer: 'set-up time',
      figure: null,
    },
    {
      id: 'ch02_fill_005',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'The central idea behind the simple batch-processing scheme is the use of a piece of software known as the _________ .',
      choices: null,
      answer: 'monitor',
      figure: null,
    },
    {
      id: 'ch02_fill_006',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'Any resource allocation and scheduling policy must consider three factors: Fairness, Differential responsiveness, and __________ .',
      choices: null,
      answer: 'Efficiency',
      figure: null,
    },
    {
      id: 'ch02_fill_007',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'A __________ is set at the beginning of each job to prevent any single job from monopolizing the system.',
      choices: null,
      answer: 'timer',
      figure: null,
    },
    {
      id: 'ch02_fill_008',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'The OS has five principal storage management responsibilities: process isolation, automatic allocation and management, support of modular programming, protection and access control, and __________ .',
      choices: null,
      answer: 'long-term storage',
      figure: null,
    },
    {
      id: 'ch02_fill_009',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'The earliest computers employed __________ processing, a name derived by the way the users have access to the systems.',
      choices: null,
      answer: 'serial',
      figure: null,
    },
    {
      id: 'ch02_fill_010',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: '__________ was designed to keep the processor and I/O devices, including storage devices, simultaneously busy to achieve maximum efficiency.',
      choices: null,
      answer: 'Multiprogramming',
      figure: null,
    },
    {
      id: 'ch02_fill_011',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'In a time-sharing, multiprogramming system, multiple users simultaneously access the system through __________ .',
      choices: null,
      answer: 'terminals',
      figure: null,
    },
    {
      id: 'ch02_fill_012',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'The principal objective of __________ is to maximize processor use.',
      choices: null,
      answer: 'Batch multiprogramming',
      figure: null,
    },
    {
      id: 'ch02_fill_013',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'Three major lines of computer system development created problems in timing and synchronization that contributed to the development of the concept of the process: multiprogramming batch operation, time sharing, and __________ .',
      choices: null,
      answer: 'real-time transaction systems',
      figure: null,
    },
    {
      id: 'ch02_fill_014',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: '___________ is a facility that allows programs to address memory from a logical point of view, without regard to the amount of main memory physically available.',
      choices: null,
      answer: 'Virtual memory',
      figure: null,
    },
    {
      id: 'ch02_fill_015',
      chapter: 2,
      source: 'testbank',
      type: 'fill',
      question: 'Security and protection as it relates to operating systems is grouped into four categories: Availability, Data integrity, Authenticity, and __________ .',
      choices: null,
      answer: 'Confidentiality',
      figure: null,
    },
  ];

  window.ALL_QUESTIONS.push(...ch02);
})();
