// ===== LECTURE 05: Mutual Exclusion and Synchronisation — TESTBANK =====

if (typeof window.ALL_QUESTIONS === 'undefined') {
  window.ALL_QUESTIONS = [];
}

(function () {
  const lec05 = [
    // ==================== TRUE / FALSE ====================
    {
      type: 'tf',
      question: 'The central themes of operating system design are all concerned with the management of processes and threads.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'It is possible in a single-processor system to not only interleave the execution of multiple processes but also to overlap them.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'In a single-processor system, processes can only be interleaved (time-shared), not truly overlapped. Overlapping (true parallelism) requires multiple processors.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'As an extension of the principles of modular design and structured programming, some applications can be effectively programmed as a set of concurrent processes.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'Race condition is a situation in which two or more processes continuously change their states in response to changes in the other process(es) without doing any useful work.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'That description is actually livelock. A race condition is when the final result depends on the relative timing/order of execution of multiple processes.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'The sharing of main memory among processes is useful to permit efficient and close interaction among processes because such sharing does not lead to any problems.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Sharing memory among processes can lead to problems such as race conditions and data corruption if it is not properly synchronized.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'When processes cooperate by communication, the various processes participate in a common effort that links all of the processes.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'Atomicity guarantees isolation from concurrent processes.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'An atomic operation executes as an indivisible unit, ensuring no intermediate state is visible to concurrent processes.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Concurrent processes do not come into conflict with each other when they are competing for the use of the same resource.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Competing concurrent processes can conflict — they must be coordinated via mutual exclusion to avoid corruption of shared resources.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Two or more processes can cooperate by means of simple signals, such that a process can be forced to stop at a specified place until it has received a specific signal.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'The functioning of a process, and the output it produces, must be independent of the speed at which its execution is carried out relative to the speed of other concurrent processes.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'A process that is waiting for access to a critical section does not consume processor time.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Spin waiting (busy-waiting) consumes the processor while waiting. Only blocking-based approaches (e.g., semaphores) relinquish the CPU while waiting.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'The case of cooperation by sharing covers processes that interact with other processes without being explicitly aware of them.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'It is possible for one process to lock the mutex and for another process to unlock it.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Unlike semaphores, a mutex must be unlocked by the same thread/process that locked it. Cross-process unlocking is not permitted.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'One of the most common problems faced in concurrent processing is the producer/consumer problem.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'Processes need to be synchronized to enforce mutual exclusion.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },

    // ==================== MULTIPLE CHOICE ====================
    {
      type: 'mcq',
      question: 'The management of multiple processes within a uniprocessor system is __________ .',
      choices: [
        'multiprogramming',
        'structured applications',
        'distributed processing',
        'multiprocessing',
      ],
      answer: 0,
      hint: 'Multiprogramming allows multiple processes to share a single processor by interleaving their execution.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A situation in which a runnable process is overlooked indefinitely by the scheduler, although it is able to proceed, is _________ .',
      choices: [
        'mutual exclusion',
        'deadlock',
        'starvation',
        'livelock',
      ],
      answer: 2,
      hint: 'Starvation means a process that is ready to run is perpetually denied access to the CPU by the scheduler.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The requirement that when one process is in a critical section that accesses shared resources, no other process may be in a critical section that accesses any of those shared resources is ________ .',
      choices: [
        'critical section',
        'livelock',
        'mutual exclusion',
        'atomic operation',
      ],
      answer: 2,
      hint: 'Mutual exclusion ensures that only one process at a time can be inside its critical section accessing the shared resource.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A means for two processes to exchange information is with the use of _________ .',
      choices: [
        'spinlocks',
        'event flags',
        'condition variables',
        'messages',
      ],
      answer: 3,
      hint: 'Message passing allows processes to directly exchange data and coordinate their activities.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A semaphore that does not specify the order in which processes are removed from the queue is a ________ semaphore.',
      choices: [
        'weak',
        'general',
        'strong',
        'binary',
      ],
      answer: 0,
      hint: 'A weak semaphore does not guarantee any particular order in which blocked processes are resumed.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A ________ occurs when multiple processes or threads read and write data items so that the final result depends on the order of execution of instructions in the multiple processes.',
      choices: [
        'atomic operation',
        'race condition',
        'livelock',
        'deadlock',
      ],
      answer: 1,
      hint: 'A race condition is when the program outcome depends on the non-deterministic ordering of concurrent operations.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A _________ is an integer value used for signaling among processes.',
      choices: [
        'semaphore',
        'message',
        'mutex',
        'atomic operation',
      ],
      answer: 0,
      hint: 'A semaphore is an integer variable used for signaling; it supports wait (decrement) and signal (increment) operations.',
      figure: null,
    },
    {
      type: 'mcq',
      question: '________ is when the sequence of instruction is guaranteed to execute as a group, or not execute at all, having no visible effect on system state.',
      choices: [
        'Critical section',
        'Mutual exclusion',
        'Atomic operation',
        'Starvation',
      ],
      answer: 2,
      hint: 'Atomicity means the operation appears instantaneous and indivisible — it either completes fully or not at all.',
      figure: null,
    },
    {
      type: 'mcq',
      question: '________ are memory words used as a synchronization mechanism.',
      choices: [
        'Semaphores',
        'Event flags',
        'Counting semaphores',
        'Mailboxes',
      ],
      answer: 1,
      hint: 'Event flags are memory words where individual bits represent specific events; they are used for lightweight synchronization.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The term _______ refers to a technique in which a process can do nothing until it gets permission to enter its critical section but continues to execute an instruction or set of instructions that tests the appropriate variable to gain entrance.',
      choices: [
        'spin waiting',
        'general semaphore',
        'critical resource',
        'message passing',
      ],
      answer: 0,
      hint: 'Spin waiting (busy-waiting) keeps the processor busy repeatedly checking a flag, wasting CPU cycles.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A _______ is a data type that is used to block a process or thread until a particular condition is true.',
      choices: [
        'deadlock',
        'general semaphore',
        'condition variable',
        'mutex',
      ],
      answer: 2,
      hint: 'A condition variable is used inside a monitor to block a thread until a specific condition is signaled by another thread.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A semaphore whose definition includes the policy that the process that has been blocked the longest is released from the queue first is called a _________ semaphore.',
      choices: [
        'general',
        'strong',
        'weak',
        'counting',
      ],
      answer: 1,
      hint: 'A strong semaphore uses FIFO ordering — the process waiting the longest is the first to be unblocked.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The ________ is a programming language construct that provides equivalent functionality to that of semaphores and is easier to control.',
      choices: [
        'atomic operation',
        'coroutine',
        'critical section',
        'monitor',
      ],
      answer: 3,
      hint: 'A monitor encapsulates shared data and operations, providing automatic mutual exclusion and condition synchronization.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Probably the most useful combination, ________ allows a process to send one or more messages to a variety of destinations as quickly as possible.',
      choices: [
        'blocking send, blocking receive',
        'nonblocking send, blocking receive',
        'nonblocking send, nonblocking receive',
        'blocking send, nonblocking receive',
      ],
      answer: 1,
      hint: 'Nonblocking send lets the sender continue immediately; blocking receive makes the receiver wait until a message arrives — this is the most common and useful combination.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A ________ relationship allows multiple server processes to provide concurrent service to multiple clients.',
      choices: [
        'many-to-many',
        'many-to-one',
        'one-to-many',
        'one-to-one',
      ],
      answer: 0,
      hint: 'A many-to-many relationship in message passing lets many clients send to many servers, enabling high concurrency.',
      figure: null,
    },

    // ==================== FILL IN THE BLANK ====================
    {
      type: 'fill',
      question: '________ arises in three different contexts: multiple applications, structured applications, and operating system structure.',
      choices: null,
      answer: 'Concurrency',
      figure: null,
    },
    {
      type: 'fill',
      question: '________ was invented to allow processing time to be dynamically shared among a number of active applications.',
      choices: null,
      answer: 'Multiprogramming',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A situation in which two or more processes are unable to proceed because each is waiting for one of the others to do something is a ________ .',
      choices: null,
      answer: 'deadlock',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In the case of competing processes three control problems must be faced: mutual exclusion, deadlock, and ________ .',
      choices: null,
      answer: 'starvation',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A _______ is a semaphore that takes on only the values of 0 and 1.',
      choices: null,
      answer: 'binary semaphore',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A situation in which multiple threads or processes read and write a shared data item and the final result depends on the relative timing of their execution is a ________ .',
      choices: null,
      answer: 'race condition',
      figure: null,
    },
    {
      type: 'fill',
      question: '________ is a function or action implemented as a sequence of one or more instructions that appears to be indivisible; no other process can see an intermediate state or interrupt the operations.',
      choices: null,
      answer: 'Atomic operation',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A ________ is a programming language construct that encapsulates variables, access procedures, and initialization code within an abstract data type.',
      choices: null,
      answer: 'monitor',
      figure: null,
    },
    {
      type: 'fill',
      question: '________ is a section of code within a process that requires access to shared resources and that must not be executed while another process is in a corresponding section of code.',
      choices: null,
      answer: 'Critical section',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In the case of _______ , processes are sharing resources without being aware of the other processes.',
      choices: null,
      answer: 'competition',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A ________ is a mutual exclusion mechanism in which a process executes in an infinite loop waiting for the value of a lock variable to indicate availability.',
      choices: null,
      answer: 'spinlock',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Only three operations may be performed on a semaphore: initialize, increment, and ________ .',
      choices: null,
      answer: 'decrement',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A monitor supports synchronization by the use of _______ that are contained within the monitor and accessible only within the monitor.',
      choices: null,
      answer: 'condition variables',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In the case of _______ , messages are not sent directly from sender to receiver but rather are sent to a shared data structure consisting of queues that can temporarily hold messages.',
      choices: null,
      answer: 'indirect addressing',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The classic concurrency problem that involves multiple readers that can read from a shared data area when no single writer is exclusively writing to it is the _______ Problem.',
      choices: null,
      answer: 'Readers/Writers',
      figure: null,
    },
  ];

  const LECTURE = 5;
  const SOURCE = 'testbank';
  window.ALL_QUESTIONS.push(...lec05.map(q => ({ ...q, lecture: LECTURE, source: SOURCE })));
})();
