// ===== LECTURE 01: Computer Systems Overview — TESTBANK =====
// Source: Operating Systems Internals and Design Principles, 8th Edition
// Testbank questions only. For student-added questions see js/student/lec01.js
// See GUIDE.md for how to add/edit questions.

if (typeof window.ALL_QUESTIONS === 'undefined') {
  window.ALL_QUESTIONS = [];
}

(function () {
  const lec01 = [
    // ==================== TRUE / FALSE ====================
    {
      type: 'tf',
      question: 'The processor controls the operation of the computer and performs its data processing functions.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'It is not possible for a communications interrupt to occur while a printer interrupt is being processed.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Interrupts can be nested. A higher-priority interrupt can occur while a lower-priority one is being processed.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'A system bus transfers data between the computer and its external environment.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The system bus transfers data between the processor, main memory, and I/O modules — not the external environment. I/O modules handle external communication.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Cache memory is invisible to the OS.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'Cache is managed by hardware and is transparent to the operating system and usually to the programmer as well.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'With interrupts, the processor can not be engaged in executing other instructions while an I/O operation is in progress.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The whole point of interrupts is to allow the processor to execute other instructions while waiting for I/O to complete.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Digital Signal Processors deal with streaming signals such as audio and video.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'The fetched instruction is loaded into the Program Counter.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The fetched instruction is loaded into the Instruction Register (IR). The Program Counter (PC) holds the address of the next instruction to be fetched.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'Interrupts are provided primarily as a way to improve processor utilization.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'The interrupt can occur at any time and therefore at any point in the execution of a user program.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'Over the years memory access speed has consistently increased more rapidly than processor speed.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Processor speed has increased more rapidly than memory access speed, which is why cache memory is needed to bridge the gap.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'An SMP can be defined as a stand-alone computer system with two or more similar processors of comparable capability.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'The Program Status Word contains status information in the form of condition codes, which are bits typically set by the programmer as a result of program operation.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Condition codes are set by the processor (hardware) as a result of operations, not by the programmer.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'An example of a multicore system is the Intel Core i7.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'In a two-level memory hierarchy the Hit Ratio is defined as the fraction of all memory accesses found in the slower memory.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The Hit Ratio is the fraction of accesses found in the faster memory (e.g., cache), not the slower one.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'The operating system acts as an interface between the computer hardware and the human user.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },

    // ==================== MULTIPLE CHOICE ====================
    {
      type: 'mcq',
      question: 'The four main structural elements of a computer system are:',
      choices: [
        'Processor, Main Memory, I/O Modules and System Bus',
        'Processor, I/O Modules, System Bus and Secondary Memory',
        'Processor, Registers, Main Memory and System Bus',
        'Processor, Registers, I/O Modules and Main Memory',
      ],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The __________ holds the address of the next instruction to be fetched.',
      choices: [
        'Accumulator (AC)',
        'Instruction Register (IR)',
        'Instruction Counter (IC)',
        'Program Counter (PC)',
      ],
      answer: 3,
      hint: 'The Program Counter (PC) always points to the next instruction to fetch.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The __________ contains the data to be written into memory and receives the data read from memory.',
      choices: [
        'I/O address register',
        'memory address register',
        'I/O buffer register',
        'memory buffer register',
      ],
      answer: 3,
      hint: 'The Memory Buffer Register (MBR) holds the data being transferred to/from memory.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Instruction processing consists of two steps:',
      choices: [
        'fetch and execute',
        'instruction and execute',
        'instruction and halt',
        'fetch and instruction',
      ],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The ___________ routine determines the nature of the interrupt and performs whatever actions are needed.',
      choices: [
        'interrupt handler',
        'instruction signal',
        'program handler',
        'interrupt signal',
      ],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The unit of data exchanged between cache and main memory is __________ .',
      choices: [
        'block size',
        'map size',
        'cache size',
        'slot size',
      ],
      answer: 0,
      hint: 'Data is transferred between cache and main memory in units called blocks (or lines).',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The _________ chooses which block to replace when a new block is to be loaded into the cache and the cache already has all slots filled with other blocks.',
      choices: [
        'memory controller',
        'mapping function',
        'write policy',
        'replacement algorithm',
      ],
      answer: 3,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: '__________ is more efficient than interrupt-driven or programmed I/O for a multiple-word I/O transfer.',
      choices: [
        'Spatial locality',
        'Direct memory access',
        'Stack access',
        'Temporal locality',
      ],
      answer: 1,
      hint: 'DMA allows data to be transferred directly between I/O and memory without involving the processor for each word.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The __________ is a point-to-point link electrical interconnect specification that enables high-speed communications among connected processor chips.',
      choices: [
        'QPI',
        'DDR3',
        'LRUA',
        'ISR',
      ],
      answer: 0,
      hint: 'QPI stands for QuickPath Interconnect, developed by Intel.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Small, fast memory located between the processor and main memory is called:',
      choices: [
        'Block memory',
        'Cache memory',
        'Direct memory',
        'WORM memory',
      ],
      answer: 1,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: 'In a uniprocessor system, multiprogramming increases processor efficiency by:',
      choices: [
        'Taking advantage of time wasted by long wait interrupt handling',
        'Disabling all interrupts except those of highest priority',
        'Eliminating all idle processor cycles',
        'Increasing processor speed',
      ],
      answer: 0,
      hint: 'Multiprogramming keeps the processor busy by switching to another program when the current one is waiting for I/O.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The two basic types of processor registers are:',
      choices: [
        'User-visible and user-invisible registers',
        'Control and user-invisible registers',
        'Control and Status registers',
        'User-visible and Control/Status registers',
      ],
      answer: 3,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: 'When an external device becomes ready to be serviced by the processor the device sends a(n) _________ signal to the processor.',
      choices: [
        'access',
        'halt',
        'handler',
        'interrupt',
      ],
      answer: 3,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: 'One mechanism Intel uses to make its caches more effective is __________ , in which the hardware examines memory access patterns and attempts to fill the caches speculatively with data that is likely to be requested soon.',
      choices: [
        'mapping',
        'handling',
        'interconnecting',
        'prefetching',
      ],
      answer: 3,
      hint: null,
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A __________ organization has a number of potential advantages over a uniprocessor organization including performance, availability, incremental growth, and scaling.',
      choices: [
        'temporal locality',
        'symmetric multiprocessor',
        'direct memory access',
        'processor status word',
      ],
      answer: 1,
      hint: null,
      figure: null,
    },

    // ==================== FILL IN THE BLANK ====================
    {
      type: 'fill',
      question: 'The invention of the _________ was the hardware revolution that brought about desktop and handheld computing.',
      choices: null,
      answer: 'microprocessor',
      figure: null,
    },
    {
      type: 'fill',
      question: 'To satisfy the requirements of handheld devices, the classic microprocessor is giving way to the _________ , where not just the CPUs and caches are on the same chip, but also many of the other components of the system, such as DSPs, GPUs, I/O devices and main memory.',
      choices: null,
      answer: 'System on a Chip (SoC)',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The processing required for a single instruction is called a(n) __________ cycle.',
      choices: null,
      answer: 'instruction',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The fetched instruction is loaded into the __________ .',
      choices: null,
      answer: 'Instruction Register (IR)',
      figure: null,
    },
    {
      type: 'fill',
      question: 'When an external device is ready to accept more data from the processor, the I/O module for that external device sends an __________ signal to the processor.',
      choices: null,
      answer: 'interrupt request',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The __________ is a device for staging the movement of data between main memory and processor registers to improve performance and is not usually visible to the programmer or processor.',
      choices: null,
      answer: 'cache',
      figure: null,
    },
    {
      type: 'fill',
      question: 'External, nonvolatile memory is also referred to as __________ or auxiliary memory.',
      choices: null,
      answer: 'secondary memory',
      figure: null,
    },
    {
      type: 'fill',
      question: 'When a new block of data is read into the cache the __________ determines which cache location the block will occupy.',
      choices: null,
      answer: 'mapping function',
      figure: null,
    },
    {
      type: 'fill',
      question: 'In a _________ multiprocessor all processors can perform the same functions so the failure of a single processor does not halt the machine.',
      choices: null,
      answer: 'symmetric',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A __________ computer combines two or more processors on a single piece of silicon.',
      choices: null,
      answer: 'multicore',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A Control/Status register that contains the address of the next instruction to be fetched is called the _________.',
      choices: null,
      answer: 'Program Counter (PC)',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Each location in Main Memory contains a _________ value that can be interpreted as either an instruction or data.',
      choices: null,
      answer: 'binary number',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A special type of address register required by a system that implements user visible stack addressing is called a __________ .',
      choices: null,
      answer: 'stack pointer',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Registers that are used by system programs to minimize main memory references by optimizing register use are called __________ .',
      choices: null,
      answer: 'user-visible registers',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The concept of multiple programs taking turns in execution is known as __________.',
      choices: null,
      answer: 'multiprogramming',
      figure: null,
    },
  ];

  const LECTURE = 1;
  const SOURCE = 'testbank';
  window.ALL_QUESTIONS.push(...lec01.map(q => ({ ...q, lecture: LECTURE, source: SOURCE })));
})();
