// ===== LECTURE 03: Process Description and Control — TESTBANK =====
// Source: Operating Systems Internals and Design Principles, 8th Edition
// Testbank questions only. For student-added questions see js/student/lec03.js
// See GUIDE.md for how to add/edit questions.

if (typeof window.ALL_QUESTIONS === 'undefined') {
  window.ALL_QUESTIONS = [];
}

(function () {
  const lec03 = [
    // ==================== TRUE / FALSE ====================
    {
      id: 'lec03_tf_001',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'A computer platform consists of a collection of hardware resources, such as the processor, main memory, I/O modules, timers, and disk drives.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_tf_002',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'For efficiency, applications should be written directly for a given hardware platform.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Applications are written to run on top of the OS, not directly on hardware. The OS provides abstraction and portability.',
      figure: null,
    },
    {
      id: 'lec03_tf_003',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'A design change in the structure or semantics of the process control block could affect a number of modules in the OS.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'The PCB is central to the OS. Many modules depend on its structure, so changes can have widespread impact.',
      figure: null,
    },
    {
      id: 'lec03_tf_004',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'The process control block is the key tool that enables the OS to support multiple processes and to provide for multiprocessing.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_tf_005',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'It is not the responsibility of the operating system to control the execution of processes.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Controlling the execution of processes is one of the principal responsibilities of the OS.',
      figure: null,
    },
    {
      id: 'lec03_tf_006',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'The first step in designing an OS to control processes is to describe the behavior that we would like the processes to exhibit.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_tf_007',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'The OS may create a process on behalf of an application.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_tf_008',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'Swapping is not an I/O operation so it will not enhance performance.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Swapping is an I/O operation (transferring processes between main memory and disk). It can enhance performance by freeing memory for other processes.',
      figure: null,
    },
    {
      id: 'lec03_tf_009',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'If a system does not employ virtual memory each process to be executed must be fully loaded into main memory.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'Without virtual memory, the entire process must fit in main memory before it can execute.',
      figure: null,
    },
    {
      id: 'lec03_tf_010',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'A process that is not in main memory is immediately available for execution, regardless of whether or not it is awaiting an event.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'A process not in main memory must first be loaded (swapped in) before it can execute. It is not immediately available.',
      figure: null,
    },
    {
      id: 'lec03_tf_011',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'The OS may suspend a process if it detects or suspects a problem.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_tf_012',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'All processor designs include a register or set of registers, often known as the program status word, which contains status information.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_tf_013',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'The process control block is the least important data structure in an OS.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'The PCB is the most important data structure in an OS. It contains all the information needed to manage a process.',
      figure: null,
    },
    {
      id: 'lec03_tf_014',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'A process switch may occur any time that the OS has gained control from the currently running process.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_tf_015',
      chapter: 3,
      source: 'testbank',
      type: 'tf',
      question: 'The principal function of the OS is to create, manage, and terminate processes.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },

    // ==================== MULTIPLE CHOICE ====================
    {
      id: 'lec03_mcq_001',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'The processor itself provides only limited support for multiprogramming, and __________ is needed to manage the sharing of the processor and other resources by multiple applications at the same time.',
      choices: [
        'memory',
        'data',
        'software',
        'hardware',
      ],
      answer: 2,
      hint: 'The OS (software) is needed to manage multiprogramming and resource sharing.',
      figure: null,
    },
    {
      id: 'lec03_mcq_002',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: '"The process was placed in a suspended state by an agent; either itself, a parent process, or the OS for the purpose of preventing its execution," is a characteristic of a _________ process.',
      choices: [
        'blocked',
        'suspended',
        'ready',
        'swapped',
      ],
      answer: 1,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_mcq_003',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'A __________ is a unit of activity characterized by the execution of a sequence of instructions, a current state, and an associated set of system resources.',
      choices: [
        'identifier',
        'process',
        'state',
        'kernel',
      ],
      answer: 1,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_mcq_004',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'We can characterize the behavior of an individual process by listing the sequence of instructions, referred to as a __________, that executes for that process.',
      choices: [
        'state',
        'trace',
        'process block',
        'priority',
      ],
      answer: 1,
      hint: 'A trace is the sequence of instructions that execute for a process, useful for analyzing process behavior.',
      figure: null,
    },
    {
      id: 'lec03_mcq_005',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'It is the principal responsibility of the __________ to control the execution of processes.',
      choices: [
        'OS',
        'process control block',
        'memory',
        'dispatcher',
      ],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_mcq_006',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'When one process spawns another, the spawned process is referred to as the __________ .',
      choices: [
        'trap process',
        'child process',
        'stack process',
        'parent process',
      ],
      answer: 1,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_mcq_007',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: '__________ involves moving part or all of a process from main memory to disk.',
      choices: [
        'Swapping',
        'Relocating',
        'Suspending',
        'Blocking',
      ],
      answer: 0,
      hint: 'Swapping moves a process (or part of it) from main memory to disk to free up memory.',
      figure: null,
    },
    {
      id: 'lec03_mcq_008',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'When a process is in the _________ state it is in secondary memory but is available for execution as soon as it is loaded into main memory.',
      choices: [
        'Blocked',
        'Blocked/Suspend',
        'Ready',
        'Ready/Suspend',
      ],
      answer: 3,
      hint: 'Ready/Suspend means the process is on disk but ready to run once swapped into main memory.',
      figure: null,
    },
    {
      id: 'lec03_mcq_009',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'A process is in the _________ state when it is in main memory and awaiting an event.',
      choices: [
        'Blocked',
        'Blocked/Suspend',
        'Ready/Suspend',
        'Ready',
      ],
      answer: 0,
      hint: 'Blocked means the process is in main memory but waiting for some event (like I/O completion).',
      figure: null,
    },
    {
      id: 'lec03_mcq_010',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'The OS must maintain __________ tables to manage processes.',
      choices: [
        'process',
        'I/O',
        'memory',
        'file',
      ],
      answer: 0,
      hint: 'The OS maintains process tables (among other tables like memory, I/O, and file tables) but the question refers specifically to managing processes.',
      figure: null,
    },
    {
      id: 'lec03_mcq_011',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'The collection of program, data, stack, and attributes is referred to as the _________ .',
      choices: [
        'process structure',
        'process control block',
        'process location',
        'process image',
      ],
      answer: 3,
      hint: 'The process image is the complete collection of program code, data, stack, and PCB attributes.',
      figure: null,
    },
    {
      id: 'lec03_mcq_012',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'The _________ is the less-privileged mode.',
      choices: [
        'user mode',
        'kernel mode',
        'system mode',
        'control mode',
      ],
      answer: 0,
      hint: 'User mode restricts access to certain instructions and memory areas. Kernel mode (system/control mode) is the more-privileged mode.',
      figure: null,
    },
    {
      id: 'lec03_mcq_013',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'The __________ contains the basic elements of a user\'s program and can be generated directly from a compiled object file.',
      choices: [
        'register context',
        'user-level context',
        'system-level context',
        'all of the above',
      ],
      answer: 1,
      hint: null,
      figure: null,
    },
    {
      id: 'lec03_mcq_014',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'A total of _________ process states are recognized by the UNIX SVR4 operating system.',
      choices: [
        '3',
        '9',
        '21',
        '15',
      ],
      answer: 1,
      hint: 'UNIX SVR4 recognizes 9 process states.',
      figure: null,
    },
    {
      id: 'lec03_mcq_015',
      chapter: 3,
      source: 'testbank',
      type: 'mcq',
      question: 'The portion of the operating system that selects the next process to run is called the _________ .',
      choices: [
        'trace',
        'process control block',
        'dispatcher',
        'PSW',
      ],
      answer: 2,
      hint: 'The dispatcher (or short-term scheduler) selects the next process from the ready queue to run on the processor.',
      figure: null,
    },

    // ==================== FILL IN THE BLANK ====================
    {
      id: 'lec03_fill_001',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'The __________ is a layer of software between the applications and the computer hardware that supports applications and utilities.',
      choices: null,
      answer: 'operating system (OS)',
      figure: null,
    },
    {
      id: 'lec03_fill_002',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'A process is in the _________ state when it is in secondary memory and awaiting an event.',
      choices: null,
      answer: 'Blocked/Suspend',
      figure: null,
    },
    {
      id: 'lec03_fill_003',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'Two essential elements of a process are __________ and a set of data associated with that code.',
      choices: null,
      answer: 'program code',
      figure: null,
    },
    {
      id: 'lec03_fill_004',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'The _________ tables provide information about the existence of files, their location on secondary memory, their current status, and other attributes.',
      choices: null,
      answer: 'file',
      figure: null,
    },
    {
      id: 'lec03_fill_005',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'A significant point about the __________ is that it contains sufficient information so that it is possible to interrupt a running process and later resume execution as if the interruption had not occurred.',
      choices: null,
      answer: 'process control block',
      figure: null,
    },
    {
      id: 'lec03_fill_006',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'General-purpose registers are _________ dependent.',
      choices: null,
      answer: 'hardware',
      figure: null,
    },
    {
      id: 'lec03_fill_007',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'When the OS creates a process at the explicit request of another process, the action is referred to as __________ .',
      choices: null,
      answer: 'process spawning',
      figure: null,
    },
    {
      id: 'lec03_fill_008',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'The process is said to be operating in a _________ fashion if each process in the queue is given a certain amount of time, in turn, to execute and then returned to the queue, unless blocked.',
      choices: null,
      answer: 'round-robin',
      figure: null,
    },
    {
      id: 'lec03_fill_009',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'A process in the _________ state is in main memory and available for execution.',
      choices: null,
      answer: 'Ready',
      figure: null,
    },
    {
      id: 'lec03_fill_010',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: '_________ tables are used to keep track of both main (real) and secondary (virtual) memory.',
      choices: null,
      answer: 'Memory',
      figure: null,
    },
    {
      id: 'lec03_fill_011',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'The process control block information can be grouped into three general categories: process identification, __________ and process control information.',
      choices: null,
      answer: 'processor state information',
      figure: null,
    },
    {
      id: 'lec03_fill_012',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'A __________ is the maximum amount of time that a process can execute before being interrupted.',
      choices: null,
      answer: 'time slice',
      figure: null,
    },
    {
      id: 'lec03_fill_013',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'When a process is not running, the processor status information is stored in the _________ context area.',
      choices: null,
      answer: 'register',
      figure: null,
    },
    {
      id: 'lec03_fill_014',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'The principal function of the OS is to create, manage, and ________ processes.',
      choices: null,
      answer: 'terminate',
      figure: null,
    },
    {
      id: 'lec03_fill_015',
      chapter: 3,
      source: 'testbank',
      type: 'fill',
      question: 'An IDS comprises three logical components: sensors, __________, and user interface.',
      choices: null,
      answer: 'analyzers',
      figure: null,
    },
  ];

  window.ALL_QUESTIONS.push(...lec03);
})();
