// ===== LECTURE 06: Deadlock and Starvation — TESTBANK =====

if (typeof window.ALL_QUESTIONS === 'undefined') {
  window.ALL_QUESTIONS = [];
}

(function () {
  const lec06 = [
    // ==================== TRUE / FALSE ====================
    {
      type: 'tf',
      question: 'Deadlock is permanent because none of the events are ever triggered.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'By definition, a deadlock is a permanent blocking — no process involved can proceed without external intervention.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'All deadlocks involve conflicting needs for resources by two or more processes.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'Interrupts, signals, messages, and information in I/O buffers are all examples of reusable resources.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'These are consumable resources — they are created by one process and consumed (destroyed) by another. Reusable resources (like memory or CPU) are not depleted by use.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'A useful tool in characterizing the allocation of resources to processes is the resource allocation graph.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'For deadlock to occur, there must not only be a fatal region, but also a sequence of resource requests that has led into the fatal region.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'An indirect method of deadlock prevention is to prevent the occurrence of a circular wait.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Preventing circular wait is a direct method. Indirect methods prevent mutual exclusion, hold-and-wait, or no-preemption conditions.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'If access to a resource requires mutual exclusion then mutual exclusion must be supported by the OS.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'The OS may preempt the second process and require it to release its resources if a process requests a resource that is currently held by another process.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'Deadlock avoidance requires knowledge of future process resource requests.',
      choices: ['True', 'False'],
      answer: 0,
      hint: 'Avoidance algorithms (like the Banker\'s Algorithm) require processes to declare their maximum resource needs in advance.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'An unsafe state is one in which there is at least one sequence of resource allocations to processes that does not result in a deadlock.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'A safe state guarantees at least one sequence that avoids deadlock. An unsafe state means no such guaranteed safe sequence exists.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'An atomic operation executes without interruption and without interference.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'Deadlock avoidance is more restrictive than deadlock prevention.',
      choices: ['True', 'False'],
      answer: 1,
      hint: 'Deadlock prevention is more restrictive because it disallows one of the four necessary conditions entirely. Avoidance is more flexible, making decisions at runtime.',
      figure: null,
    },
    {
      type: 'tf',
      question: 'The dining philosophers\' problem can be representative of problems dealing with the coordination of shared resources which may occur when an application includes concurrent threads of execution.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'A signal is similar to a hardware interrupt but does not employ priorities.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },
    {
      type: 'tf',
      question: 'A mutex is used to ensure that only one thread at a time can access the resource protected by the mutex.',
      choices: ['True', 'False'],
      answer: 0,
      hint: null,
      figure: null,
    },

    // ==================== MULTIPLE CHOICE ====================
    {
      type: 'mcq',
      question: 'A set of processes is _________ when each process in the set is blocked awaiting an event that can only be triggered by another blocked process in the set.',
      choices: [
        'spinlocked',
        'stagnant',
        'preempted',
        'deadlocked',
      ],
      answer: 3,
      hint: 'Deadlock is a circular wait where each blocked process is waiting for a resource held by another blocked process.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Examples of __________ include processors, I/O channels, main and secondary memory, devices, and data structures such as files, databases, and semaphores.',
      choices: [
        'regional resources',
        'joint resources',
        'reusable resources',
        'consumable resources',
      ],
      answer: 2,
      hint: 'Reusable resources can be used repeatedly by processes without being depleted — hardware and OS data structures fall into this category.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'With _________ only one process may use a resource at a time and no process may access a resource unit that has been allocated to another process.',
      choices: [
        'hold and wait',
        'mutual exclusion',
        'no preemption',
        'circular wait',
      ],
      answer: 1,
      hint: 'Mutual exclusion means exclusive access — only one process can hold the resource at any given time.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A closed chain of processes exists, such that each process holds at least one resource needed by the next process in the chain is the condition of __________ .',
      choices: [
        'no preemption',
        'mutual exclusion',
        'circular wait',
        'hold and wait',
      ],
      answer: 2,
      hint: 'Circular wait is the condition where processes form a cycle, each holding a resource that the next one needs.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Once the processes have progressed into the __________ , those processes will deadlock.',
      choices: [
        'fatal region',
        'regional resources',
        'spinlock',
        'hold and wait',
      ],
      answer: 0,
      hint: 'The fatal region in a joint progress diagram is the area that inevitably leads to deadlock once entered.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The strategy of deadlock _________ is to design a system in such a way that the possibility of deadlock is excluded.',
      choices: [
        'prevention',
        'detection',
        'diversion',
        'avoidance',
      ],
      answer: 0,
      hint: 'Deadlock prevention eliminates one or more of the four necessary conditions for deadlock at the design stage.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The _________ condition can be prevented by requiring that a process request all of its required resources at one time and blocking the process until all requests can be granted simultaneously.',
      choices: [
        'mutual exclusion',
        'hold and wait',
        'circular wait',
        'no preemption',
      ],
      answer: 1,
      hint: 'The hold-and-wait condition is eliminated by requiring processes to request all needed resources upfront before execution begins.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The fastest form of interprocess communication provided in UNIX is __________ .',
      choices: [
        'shared memory',
        'message',
        'pipe',
        'semaphore',
      ],
      answer: 0,
      hint: 'Shared memory is the fastest IPC mechanism because data is accessed directly without copying through the kernel.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The __________ condition can be prevented by defining a linear ordering of resource types.',
      choices: [
        'hold and wait',
        'no preemption',
        'mutual exclusion',
        'circular wait',
      ],
      answer: 3,
      hint: 'Defining a total ordering of resources and requiring processes to request them in that order prevents circular wait.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'Requested resources are granted to processes whenever possible with _________ .',
      choices: [
        'preemption',
        'deadlock detection',
        'mutual exclusion',
        'deadlock avoidance',
      ],
      answer: 1,
      hint: 'With deadlock detection, the system grants resources freely and later detects and resolves any deadlock that occurs.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'One of the most significant contributions of UNIX to the development of operating systems is the _________ .',
      choices: [
        'semaphore',
        'shared memory',
        'message',
        'pipe',
      ],
      answer: 3,
      hint: 'The pipe is one of UNIX\'s most iconic inventions, enabling chaining of processes for data streaming.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'A __________ is a software mechanism that informs a process of the occurrence of asynchronous events.',
      choices: [
        'signal',
        'message',
        'mailbox',
        'kernel',
      ],
      answer: 0,
      hint: 'Signals are software-level interrupts used in UNIX/Linux to notify processes of events such as errors or external triggers.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The most common technique used for protecting a critical section in Linux is the _______ .',
      choices: [
        'signal',
        'atomic bitmap operation',
        'atomic integer operation',
        'spinlock',
      ],
      answer: 3,
      hint: 'Spinlocks are the most widely used mechanism in the Linux kernel for short critical section protection on multiprocessor systems.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The _________ allows multiple threads to have simultaneous read-only access to an object protected by the lock.',
      choices: [
        'barrier',
        'condition variable',
        'readers/writer lock',
        'mutex',
      ],
      answer: 2,
      hint: 'A readers/writer lock grants concurrent read access to many threads but requires exclusive access for writers.',
      figure: null,
    },
    {
      type: 'mcq',
      question: 'The _________ is useful in sending a signal to a thread indicating that a particular event has occurred.',
      choices: [
        'mutex object',
        'semaphore object',
        'event object',
        'waitable timer object',
      ],
      answer: 2,
      hint: 'An event object is a synchronization primitive in Windows that is used to notify threads when a specific event occurs.',
      figure: null,
    },

    // ==================== FILL IN THE BLANK ====================
    {
      type: 'fill',
      question: '_________ can be defined as the permanent blocking of a set of processes that either compete for system resources or communicate with each other.',
      choices: null,
      answer: 'Deadlock',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A _________ resource is one that can be safely used by only one process at a time and is not depleted by that use.',
      choices: null,
      answer: 'reusable',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A _________ resource is one that can be created and destroyed.',
      choices: null,
      answer: 'consumable',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The _________ is a directed graph that depicts a state of the system of resources and processes, with each process and each resource represented by a node.',
      choices: null,
      answer: 'resource allocation graph',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Three conditions of policy must be present for a deadlock to be possible: mutual exclusion, no preemption, and _________ .',
      choices: null,
      answer: 'hold and wait',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Three general approaches exist for dealing with deadlock: prevent, avoid, and __________ .',
      choices: null,
      answer: 'detect',
      figure: null,
    },
    {
      type: 'fill',
      question: '__________ allows the three necessary conditions but makes judicious choices to assure that the deadlock point is never reached.',
      choices: null,
      answer: 'Deadlock avoidance',
      figure: null,
    },
    {
      type: 'fill',
      question: 'The strategy of resource allocation denial is referred to as the ___________ .',
      choices: null,
      answer: "banker's algorithm",
      figure: null,
    },
    {
      type: 'fill',
      question: 'The _________ of the system reflects the current allocation of resources to processes.',
      choices: null,
      answer: 'state',
      figure: null,
    },
    {
      type: 'fill',
      question: '_________ strategies are very conservative and solve the problem of deadlock by limiting access to resources and by imposing restrictions on processes.',
      choices: null,
      answer: 'Deadlock prevention',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Inspired by the concept of co-routines, a _________ is a circular buffer allowing two processes to communicate on the producer-consumer model.',
      choices: null,
      answer: 'pipe',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Two types of atomic operations are defined in Linux: integer operations and __________ .',
      choices: null,
      answer: 'bitmap operations',
      figure: null,
    },
    {
      type: 'fill',
      question: 'Linux provides three types of semaphore facilities in the kernel: binary semaphores, counting semaphores, and __________ .',
      choices: null,
      answer: 'reader-writer semaphores',
      figure: null,
    },
    {
      type: 'fill',
      question: 'An executable entity within a process is a __________ object.',
      choices: null,
      answer: 'thread',
      figure: null,
    },
    {
      type: 'fill',
      question: 'A program invocation, including the address space and resources required to run the program, is a __________ object.',
      choices: null,
      answer: 'process',
      figure: null,
    },
  ];

  const LECTURE = 6;
  const SOURCE = 'testbank';
  window.ALL_QUESTIONS.push(...lec06.map(q => ({ ...q, lecture: LECTURE, source: SOURCE })));
})();
